-include ../build-config

ROOT=../../

all:
	cd $(ROOT); $(MAKE) javadoc

clean:
	\rm -rf  gov
	\rm  -f  allclasses-frame.html
	\rm  -f  deprecated-list.html 
	\rm  -f  sdp_announceParser.html  
	\rm  -f  serialized-form.html  
	\rm  -f  sip_messageParser.html  
	\rm  -f  overview-*.html 
	\rm  -f  help-doc.html
	\rm  -rf index-files
	\rm  -f  packages.html
	\rm  -f  sdp_announceParser.html
	\rm  -f  sip_messageParser.html
	\rm  -f  stylesheet.css 
	\rm  -f  index.html 
	\rm  -f  package-list
