/*******************************************************************************
* Product of NIST/ITL Advanced Networking Technologies Division (ANTD)         *
* See ../../../../doc/uncopyright.html for conditions of use                   *
* Author: M. Ranganathan (mranga@nist.gov)                                     *
* Questions/Comments: nist-sip-dev@antd.nist.gov                               *
*******************************************************************************/
package gov.nist.sip.msgparser;
import gov.nist.sip.net.*;
import java.util.*;
/**
* Interface  that provides methods for processing good 
* and bad messages for the PipelinedMessageParser.
* @see PipelinedMsgParser
*/

public interface SIPMessageListener  extends SIPParseExceptionListener
{
	/**
	* This is called from the parser on successful message processing.
	* @see SIPParseExceptionListener for the method that gets called 
	*	on parse exception.
	* @param msg  SIP Message structure that is generated by the parser.
	*/
	public void processMessage(SIPMessage msg);
}
