/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_parray[] = "\
proc parray {a {pattern *}} {\n\
upvar 1 $a array\n\
if {![array exists array]} {\n\
error \"\\\"$a\\\" isn't an array\"\n\
}\n\
set maxl 0\n\
foreach name [lsort [array names array $pattern]] {\n\
if {[string length $name] > $maxl} {\n\
set maxl [string length $name]\n\
}\n\
}\n\
set maxl [expr {$maxl + [string length $a] + 2}]\n\
foreach name [lsort [array names array $pattern]] {\n\
set nameString [format %s(%s) $a $name]\n\
puts stdout [format \"%-*s = %s\" $maxl $nameString $array($name)]\n\
}\n\
}\n\
";
