/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_tkfbox[] = "\
proc tkIconList {w args} {\n\
upvar #0 $w data\n\
tkIconList_Config $w $args\n\
tkIconList_Create $w\n\
}\n\
proc tkIconList_Config {w argList} {\n\
upvar #0 $w data\n\
set specs {\n\
{-browsecmd \"\" \"\" \"\"}\n\
{-command \"\" \"\" \"\"}\n\
}\n\
tclParseConfigSpec $w $specs \"\" $argList\n\
}\n\
proc tkIconList_Create {w} {\n\
upvar #0 $w data\n\
frame $w\n\
set data(sbar)   [scrollbar $w.sbar -orient horizontal \\\n\
-highlightthickness 0 -takefocus 0]\n\
set data(canvas) [canvas $w.canvas -bd 2 -relief sunken \\\n\
-width 400 -height 120 -takefocus 1]\n\
pack $data(sbar) -side bottom -fill x -padx 2\n\
pack $data(canvas) -expand yes -fill both\n\
$data(sbar) config -command \"$data(canvas) xview\"\n\
$data(canvas) config -xscrollcommand \"$data(sbar) set\"\n\
set data(maxIW) 1\n\
set data(maxIH) 1\n\
set data(maxTW) 1\n\
set data(maxTH) 1\n\
set data(numItems) 0\n\
set data(curItem)  {}\n\
set data(noScroll) 1\n\
bind $data(canvas) <Configure> \"tkIconList_Arrange $w\"\n\
bind $data(canvas) <1>         \"tkIconList_Btn1 $w %x %y\"\n\
bind $data(canvas) <B1-Motion> \"tkIconList_Motion1 $w %x %y\"\n\
bind $data(canvas) <Double-1>  \"tkIconList_Double1 $w %x %y\"\n\
bind $data(canvas) <ButtonRelease-1> \"tkCancelRepeat\"\n\
bind $data(canvas) <B1-Leave>  \"tkIconList_Leave1 $w %x %y\"\n\
bind $data(canvas) <B1-Enter>  \"tkCancelRepeat\"\n\
bind $data(canvas) <Up>        \"tkIconList_UpDown $w -1\"\n\
bind $data(canvas) <Down>      \"tkIconList_UpDown $w  1\"\n\
bind $data(canvas) <Left>      \"tkIconList_LeftRight $w -1\"\n\
bind $data(canvas) <Right>     \"tkIconList_LeftRight $w  1\"\n\
bind $data(canvas) <Return>    \"tkIconList_ReturnKey $w\"\n\
bind $data(canvas) <KeyPress>  \"tkIconList_KeyPress $w %A\"\n\
bind $data(canvas) <Control-KeyPress> \";\"\n\
bind $data(canvas) <Alt-KeyPress>  \";\"\n\
bind $data(canvas) <FocusIn>   \"tkIconList_FocusIn $w\"\n\
return $w\n\
}\n\
proc tkIconList_AutoScan {w} {\n\
upvar #0 $w data\n\
global tkPriv\n\
if {![winfo exists $w]} return\n\
set x $tkPriv(x)\n\
set y $tkPriv(y)\n\
if {$data(noScroll)} {\n\
return\n\
}\n\
if {$x >= [winfo width $data(canvas)]} {\n\
$data(canvas) xview scroll 1 units\n\
} elseif {$x < 0} {\n\
$data(canvas) xview scroll -1 units\n\
} elseif {$y >= [winfo height $data(canvas)]} {\n\
} elseif {$y < 0} {\n\
} else {\n\
return\n\
}\n\
tkIconList_Motion1 $w $x $y\n\
set tkPriv(afterId) [after 50 tkIconList_AutoScan $w]\n\
}\n\
proc tkIconList_DeleteAll {w} {\n\
upvar #0 $w data\n\
upvar #0 $w:itemList itemList\n\
$data(canvas) delete all\n\
catch {unset data(selected)}\n\
catch {unset data(rect)}\n\
catch {unset data(list)}\n\
catch {unset itemList}\n\
set data(maxIW) 1\n\
set data(maxIH) 1\n\
set data(maxTW) 1\n\
set data(maxTH) 1\n\
set data(numItems) 0\n\
set data(curItem)  {}\n\
set data(noScroll) 1\n\
$data(sbar) set 0.0 1.0\n\
$data(canvas) xview moveto 0\n\
}\n\
proc tkIconList_Add {w image text} {\n\
upvar #0 $w data\n\
upvar #0 $w:itemList itemList\n\
upvar #0 $w:textList textList\n\
set iTag [$data(canvas) create image 0 0 -image $image -anchor nw]\n\
set tTag [$data(canvas) create text  0 0 -text  $text  -anchor nw \\\n\
-font $data(font)]\n\
set rTag [$data(canvas) create rect  0 0 0 0 -fill \"\" -outline \"\"]\n\
set b [$data(canvas) bbox $iTag]\n\
set iW [expr {[lindex $b 2]-[lindex $b 0]}]\n\
set iH [expr {[lindex $b 3]-[lindex $b 1]}]\n\
if {$data(maxIW) < $iW} {\n\
set data(maxIW) $iW\n\
}\n\
if {$data(maxIH) < $iH} {\n\
set data(maxIH) $iH\n\
}\n\
set b [$data(canvas) bbox $tTag]\n\
set tW [expr {[lindex $b 2]-[lindex $b 0]}]\n\
set tH [expr {[lindex $b 3]-[lindex $b 1]}]\n\
if {$data(maxTW) < $tW} {\n\
set data(maxTW) $tW\n\
}\n\
if {$data(maxTH) < $tH} {\n\
set data(maxTH) $tH\n\
}\n\
lappend data(list) [list $iTag $tTag $rTag $iW $iH $tW $tH $data(numItems)]\n\
set itemList($rTag) [list $iTag $tTag $text $data(numItems)]\n\
set textList($data(numItems)) [string tolower $text]\n\
incr data(numItems)\n\
}\n\
proc tkIconList_Arrange {w} {\n\
upvar #0 $w data\n\
if {![info exists data(list)]} {\n\
if {[info exists data(canvas)] && [winfo exists $data(canvas)]} {\n\
set data(noScroll) 1\n\
$data(sbar) config -command \"\"\n\
}\n\
return\n\
}\n\
set W [winfo width  $data(canvas)]\n\
set H [winfo height $data(canvas)]\n\
set pad [expr {[$data(canvas) cget -highlightthickness] + \\\n\
[$data(canvas) cget -bd]}]\n\
if {$pad < 2} {\n\
set pad 2\n\
}\n\
incr W -[expr {$pad*2}]\n\
incr H -[expr {$pad*2}]\n\
set dx [expr {$data(maxIW) + $data(maxTW) + 8}]\n\
if {$data(maxTH) > $data(maxIH)} {\n\
set dy $data(maxTH)\n\
} else {\n\
set dy $data(maxIH)\n\
}\n\
incr dy 2\n\
set shift [expr {$data(maxIW) + 4}]\n\
set x [expr {$pad * 2}]\n\
set y [expr {$pad * 1}] ; # Why * 1 ?\n\
set usedColumn 0\n\
foreach sublist $data(list) {\n\
set usedColumn 1\n\
set iTag [lindex $sublist 0]\n\
set tTag [lindex $sublist 1]\n\
set rTag [lindex $sublist 2]\n\
set iW   [lindex $sublist 3]\n\
set iH   [lindex $sublist 4]\n\
set tW   [lindex $sublist 5]\n\
set tH   [lindex $sublist 6]\n\
set i_dy [expr {($dy - $iH)/2}]\n\
set t_dy [expr {($dy - $tH)/2}]\n\
$data(canvas) coords $iTag $x                    [expr {$y + $i_dy}]\n\
$data(canvas) coords $tTag [expr {$x + $shift}]  [expr {$y + $t_dy}]\n\
$data(canvas) coords $tTag [expr {$x + $shift}]  [expr {$y + $t_dy}]\n\
$data(canvas) coords $rTag $x $y [expr {$x+$dx}] [expr {$y+$dy}]\n\
incr y $dy\n\
if {($y + $dy) > $H} {\n\
set y [expr {$pad * 1}] ; # *1 ?\n\
incr x $dx\n\
set usedColumn 0\n\
}\n\
}\n\
if {$usedColumn} {\n\
set sW [expr {$x + $dx}]\n\
} else {\n\
set sW $x\n\
}\n\
if {$sW < $W} {\n\
$data(canvas) config -scrollregion \"$pad $pad $sW $H\"\n\
$data(sbar) config -command \"\"\n\
$data(canvas) xview moveto 0\n\
set data(noScroll) 1\n\
} else {\n\
$data(canvas) config -scrollregion \"$pad $pad $sW $H\"\n\
$data(sbar) config -command \"$data(canvas) xview\"\n\
set data(noScroll) 0\n\
}\n\
set data(itemsPerColumn) [expr {($H-$pad)/$dy}]\n\
if {$data(itemsPerColumn) < 1} {\n\
set data(itemsPerColumn) 1\n\
}\n\
if {$data(curItem) != {}} {\n\
tkIconList_Select $w [lindex [lindex $data(list) $data(curItem)] 2] 0\n\
}\n\
}\n\
proc tkIconList_Invoke {w} {\n\
upvar #0 $w data\n\
if {[string compare $data(-command) \"\"] && [info exists data(selected)]} {\n\
eval $data(-command)\n\
}\n\
}\n\
proc tkIconList_See {w rTag} {\n\
upvar #0 $w data\n\
upvar #0 $w:itemList itemList\n\
if {$data(noScroll)} {\n\
return\n\
}\n\
set sRegion [$data(canvas) cget -scrollregion]\n\
if {![string compare $sRegion {}]} {\n\
return\n\
}\n\
if {![info exists itemList($rTag)]} {\n\
return\n\
}\n\
set bbox [$data(canvas) bbox $rTag]\n\
set pad [expr {[$data(canvas) cget -highlightthickness] + \\\n\
[$data(canvas) cget -bd]}]\n\
set x1 [lindex $bbox 0]\n\
set x2 [lindex $bbox 2]\n\
incr x1 -[expr {$pad * 2}]\n\
incr x2 -[expr {$pad * 1}] ; # *1 ?\n\
set cW [expr {[winfo width $data(canvas)] - $pad*2}]\n\
set scrollW [expr {[lindex $sRegion 2]-[lindex $sRegion 0]+1}]\n\
set dispX [expr {int([lindex [$data(canvas) xview] 0]*$scrollW)}]\n\
set oldDispX $dispX\n\
if {($x2 - $dispX) >= $cW} {\n\
set dispX [expr {$x2 - $cW}]\n\
}\n\
if {($x1 - $dispX) < 0} {\n\
set dispX $x1\n\
}\n\
if {$oldDispX != $dispX} {\n\
set fraction [expr {double($dispX)/double($scrollW)}]\n\
$data(canvas) xview moveto $fraction\n\
}\n\
}\n\
proc tkIconList_SelectAtXY {w x y} {\n\
upvar #0 $w data\n\
tkIconList_Select $w [$data(canvas) find closest \\\n\
[$data(canvas) canvasx $x] [$data(canvas) canvasy $y]]\n\
}\n\
proc tkIconList_Select {w rTag {callBrowse 1}} {\n\
upvar #0 $w data\n\
upvar #0 $w:itemList itemList\n\
if {![info exists itemList($rTag)]} {\n\
return\n\
}\n\
set iTag   [lindex $itemList($rTag) 0]\n\
set tTag   [lindex $itemList($rTag) 1]\n\
set text   [lindex $itemList($rTag) 2]\n\
set serial [lindex $itemList($rTag) 3]\n\
if {![info exists data(rect)]} {\n\
set data(rect) [$data(canvas) create rect 0 0 0 0 \\\n\
-fill #a0a0ff -outline #a0a0ff]\n\
}\n\
$data(canvas) lower $data(rect)\n\
set bbox [$data(canvas) bbox $tTag]\n\
eval $data(canvas) coords $data(rect) $bbox\n\
set data(curItem) $serial\n\
set data(selected) $text\n\
if {$callBrowse} {\n\
if {[string compare $data(-browsecmd) \"\"]} {\n\
eval $data(-browsecmd) [list $text]\n\
}\n\
}\n\
}\n\
proc tkIconList_Unselect {w} {\n\
upvar #0 $w data\n\
if {[info exists data(rect)]} {\n\
$data(canvas) delete $data(rect)\n\
unset data(rect)\n\
}\n\
if {[info exists data(selected)]} {\n\
unset data(selected)\n\
}\n\
set data(curItem)  {}\n\
}\n\
proc tkIconList_Get {w} {\n\
upvar #0 $w data\n\
if {[info exists data(selected)]} {\n\
return $data(selected)\n\
} else {\n\
return \"\"\n\
}\n\
}\n\
proc tkIconList_Btn1 {w x y} {\n\
upvar #0 $w data\n\
focus $data(canvas)\n\
tkIconList_SelectAtXY $w $x $y\n\
}\n\
proc tkIconList_Motion1 {w x y} {\n\
global tkPriv\n\
set tkPriv(x) $x\n\
set tkPriv(y) $y\n\
tkIconList_SelectAtXY $w $x $y\n\
}\n\
proc tkIconList_Double1 {w x y} {\n\
upvar #0 $w data\n\
if {$data(curItem) != {}} {\n\
tkIconList_Invoke $w\n\
}\n\
}\n\
proc tkIconList_ReturnKey {w} {\n\
tkIconList_Invoke $w\n\
}\n\
proc tkIconList_Leave1 {w x y} {\n\
global tkPriv\n\
set tkPriv(x) $x\n\
set tkPriv(y) $y\n\
tkIconList_AutoScan $w\n\
}\n\
proc tkIconList_FocusIn {w} {\n\
upvar #0 $w data\n\
if {![info exists data(list)]} {\n\
return\n\
}\n\
if {$data(curItem) == {}} {\n\
set rTag [lindex [lindex $data(list) 0] 2]\n\
tkIconList_Select $w $rTag\n\
}\n\
}\n\
proc tkIconList_UpDown {w amount} {\n\
upvar #0 $w data\n\
if {![info exists data(list)]} {\n\
return\n\
}\n\
if {$data(curItem) == {}} {\n\
set rTag [lindex [lindex $data(list) 0] 2]\n\
} else {\n\
set oldRTag [lindex [lindex $data(list) $data(curItem)] 2]\n\
set rTag [lindex [lindex $data(list) [expr {$data(curItem)+$amount}]] 2]\n\
if {![string compare $rTag \"\"]} {\n\
set rTag $oldRTag\n\
}\n\
}\n\
if {[string compare $rTag \"\"]} {\n\
tkIconList_Select $w $rTag\n\
tkIconList_See $w $rTag\n\
}\n\
}\n\
proc tkIconList_LeftRight {w amount} {\n\
upvar #0 $w data\n\
if {![info exists data(list)]} {\n\
return\n\
}\n\
if {$data(curItem) == {}} {\n\
set rTag [lindex [lindex $data(list) 0] 2]\n\
} else {\n\
set oldRTag [lindex [lindex $data(list) $data(curItem)] 2]\n\
set newItem [expr {$data(curItem)+($amount*$data(itemsPerColumn))}]\n\
set rTag [lindex [lindex $data(list) $newItem] 2]\n\
if {![string compare $rTag \"\"]} {\n\
set rTag $oldRTag\n\
}\n\
}\n\
if {[string compare $rTag \"\"]} {\n\
tkIconList_Select $w $rTag\n\
tkIconList_See $w $rTag\n\
}\n\
}\n\
proc tkIconList_KeyPress {w key} {\n\
global tkPriv\n\
append tkPriv(ILAccel,$w) $key\n\
tkIconList_Goto $w $tkPriv(ILAccel,$w)\n\
catch {\n\
after cancel $tkPriv(ILAccel,$w,afterId)\n\
}\n\
set tkPriv(ILAccel,$w,afterId) [after 500 tkIconList_Reset $w]\n\
}\n\
proc tkIconList_Goto {w text} {\n\
upvar #0 $w data\n\
upvar #0 $w:textList textList\n\
global tkPriv\n\
if {![info exists data(list)]} {\n\
return\n\
}\n\
if {[string length $text] == 0} {\n\
return\n\
}\n\
if {$data(curItem) == {} || $data(curItem) == 0} {\n\
set start  0\n\
} else {\n\
set start  $data(curItem)\n\
}\n\
set text [string tolower $text]\n\
set theIndex -1\n\
set less 0\n\
set len [string length $text]\n\
set len0 [expr {$len-1}]\n\
set i $start\n\
while 1 {\n\
set sub [string range $textList($i) 0 $len0]\n\
if {[string compare $text $sub] == 0} {\n\
set theIndex $i\n\
break\n\
}\n\
incr i\n\
if {$i == $data(numItems)} {\n\
set i 0\n\
}\n\
if {$i == $start} {\n\
break\n\
}\n\
}\n\
if {$theIndex > -1} {\n\
set rTag [lindex [lindex $data(list) $theIndex] 2]\n\
tkIconList_Select $w $rTag 0\n\
tkIconList_See $w $rTag\n\
}\n\
}\n\
proc tkIconList_Reset {w} {\n\
global tkPriv\n\
catch {unset tkPriv(ILAccel,$w)}\n\
}\n\
proc tkFDialog {args} {\n\
global tkPriv\n\
set w __tk_filedialog\n\
upvar #0 $w data\n\
if {![string compare [lindex [info level 0] 0] tk_getOpenFile]} {\n\
set type open\n\
} else {\n\
set type save\n\
}\n\
tkFDialog_Config $w $type $args\n\
if {![string compare $data(-parent) .]} {\n\
set w .$w\n\
} else {\n\
set w $data(-parent).$w\n\
}\n\
if {![winfo exists $w]} {\n\
tkFDialog_Create $w\n\
} elseif {[string compare [winfo class $w] TkFDialog]} {\n\
destroy $w\n\
tkFDialog_Create $w\n\
} else {\n\
set data(dirMenuBtn) $w.f1.menu\n\
set data(dirMenu) $w.f1.menu.menu\n\
set data(upBtn) $w.f1.up\n\
set data(icons) $w.icons\n\
set data(ent) $w.f2.ent\n\
set data(typeMenuLab) $w.f3.lab\n\
set data(typeMenuBtn) $w.f3.menu\n\
set data(typeMenu) $data(typeMenuBtn).m\n\
set data(okBtn) $w.f2.ok\n\
set data(cancelBtn) $w.f3.cancel\n\
}\n\
wm transient $w $data(-parent)\n\
if {$data(-filetypes) != {}} {\n\
$data(typeMenu) delete 0 end\n\
foreach type $data(-filetypes) {\n\
set title  [lindex $type 0]\n\
set filter [lindex $type 1]\n\
$data(typeMenu) add command -label $title \\\n\
-command [list tkFDialog_SetFilter $w $type]\n\
}\n\
tkFDialog_SetFilter $w [lindex $data(-filetypes) 0]\n\
$data(typeMenuBtn) config -state normal\n\
$data(typeMenuLab) config -state normal\n\
} else {\n\
set data(filter) \"*\"\n\
$data(typeMenuBtn) config -state disabled -takefocus 0\n\
$data(typeMenuLab) config -state disabled\n\
}\n\
tkFDialog_UpdateWhenIdle $w\n\
wm withdraw $w\n\
update idletasks\n\
set x [expr {[winfo screenwidth $w]/2 - [winfo reqwidth $w]/2 \\\n\
- [winfo vrootx [winfo parent $w]]}]\n\
set y [expr {[winfo screenheight $w]/2 - [winfo reqheight $w]/2 \\\n\
- [winfo vrooty [winfo parent $w]]}]\n\
wm geom $w [winfo reqwidth $w]x[winfo reqheight $w]+$x+$y\n\
wm deiconify $w\n\
wm title $w $data(-title)\n\
set oldFocus [focus]\n\
set oldGrab [grab current $w]\n\
if {$oldGrab != \"\"} {\n\
set grabStatus [grab status $oldGrab]\n\
}\n\
grab $w\n\
focus $data(ent)\n\
$data(ent) delete 0 end\n\
$data(ent) insert 0 $data(selectFile)\n\
$data(ent) select from 0\n\
$data(ent) select to   end\n\
$data(ent) icursor end\n\
tkwait variable tkPriv(selectFilePath)\n\
catch {focus $oldFocus}\n\
grab release $w\n\
wm withdraw $w\n\
if {$oldGrab != \"\"} {\n\
if {$grabStatus == \"global\"} {\n\
grab -global $oldGrab\n\
} else {\n\
grab $oldGrab\n\
}\n\
}\n\
return $tkPriv(selectFilePath)\n\
}\n\
proc tkFDialog_Config {w type argList} {\n\
upvar #0 $w data\n\
set data(type) $type\n\
set specs {\n\
{-defaultextension \"\" \"\" \"\"}\n\
{-filetypes \"\" \"\" \"\"}\n\
{-initialdir \"\" \"\" \"\"}\n\
{-initialfile \"\" \"\" \"\"}\n\
{-parent \"\" \"\" \".\"}\n\
{-title \"\" \"\" \"\"}\n\
}\n\
if {![info exists data(selectPath)]} {\n\
set data(selectPath) [pwd]\n\
set data(selectFile) \"\"\n\
}\n\
tclParseConfigSpec $w $specs \"\" $argList\n\
if {![string compare $data(-title) \"\"]} {\n\
if {![string compare $type \"open\"]} {\n\
set data(-title) \"Open\"\n\
} else {\n\
set data(-title) \"Save As\"\n\
}\n\
}\n\
if {[string compare $data(-initialdir) \"\"]} {\n\
if {[file isdirectory $data(-initialdir)]} {\n\
set data(selectPath) [glob $data(-initialdir)]\n\
} else {\n\
set data(selectPath) [pwd]\n\
}\n\
set old [pwd]\n\
cd $data(selectPath)\n\
set data(selectPath) [pwd]\n\
cd $old\n\
}\n\
set data(selectFile) $data(-initialfile)\n\
set data(-filetypes) [tkFDGetFileTypes $data(-filetypes)]\n\
if {![winfo exists $data(-parent)]} {\n\
error \"bad window path name \\\"$data(-parent)\\\"\"\n\
}\n\
}\n\
proc tkFDialog_Create {w} {\n\
set dataName [lindex [split $w .] end]\n\
upvar #0 $dataName data\n\
global tk_library\n\
toplevel $w -class TkFDialog\n\
set f1 [frame $w.f1]\n\
label $f1.lab -text \"Directory:\" -under 0\n\
set data(dirMenuBtn) $f1.menu\n\
set data(dirMenu) [tk_optionMenu $f1.menu [format %s(selectPath) $dataName] \"\"]\n\
set data(upBtn) [button $f1.up]\n\
if {![info exists tkPriv(updirImage)]} {\n\
set tkPriv(updirImage) [image create bitmap -data {#define updir_width 28 #define updir_height 16\n\
static char updir_bits[] = {\n\
0x00, 0x00, 0x00, 0x00, 0x80, 0x1f, 0x00, 0x00, 0x40, 0x20, 0x00, 0x00,\n\
0x20, 0x40, 0x00, 0x00, 0xf0, 0xff, 0xff, 0x01, 0x10, 0x00, 0x00, 0x01,\n\
0x10, 0x02, 0x00, 0x01, 0x10, 0x07, 0x00, 0x01, 0x90, 0x0f, 0x00, 0x01,\n\
0x10, 0x02, 0x00, 0x01, 0x10, 0x02, 0x00, 0x01, 0x10, 0x02, 0x00, 0x01,\n\
0x10, 0xfe, 0x07, 0x01, 0x10, 0x00, 0x00, 0x01, 0x10, 0x00, 0x00, 0x01,\n\
0xf0, 0xff, 0xff, 0x01};}]\n\
}\n\
$data(upBtn) config -image $tkPriv(updirImage)\n\
$f1.menu config -takefocus 1 -highlightthickness 2\n\
pack $data(upBtn) -side right -padx 4 -fill both\n\
pack $f1.lab -side left -padx 4 -fill both\n\
pack $f1.menu -expand yes -fill both -padx 4\n\
set data(icons) [tkIconList $w.icons \\\n\
-browsecmd \"tkFDialog_ListBrowse $w\" \\\n\
-command   \"tkFDialog_OkCmd $w\"]\n\
set f2 [frame $w.f2 -bd 0]\n\
label $f2.lab -text \"File name:\" -anchor e -width 14 -under 5 -pady 0\n\
set data(ent) [entry $f2.ent]\n\
global $w.icons\n\
set $w.icons(font) [$data(ent) cget -font]\n\
set f3 [frame $w.f3 -bd 0]\n\
set data(typeMenuLab) [button $f3.lab -text \"Files of type:\" \\\n\
-anchor e -width 14 -under 9 \\\n\
-bd [$f2.lab cget -bd] \\\n\
-highlightthickness [$f2.lab cget -highlightthickness] \\\n\
-relief [$f2.lab cget -relief] \\\n\
-padx [$f2.lab cget -padx] \\\n\
-pady [$f2.lab cget -pady]]\n\
bindtags $data(typeMenuLab) [list $data(typeMenuLab) Label \\\n\
[winfo toplevel $data(typeMenuLab)] all]\n\
set data(typeMenuBtn) [menubutton $f3.menu -indicatoron 1 -menu $f3.menu.m]\n\
set data(typeMenu) [menu $data(typeMenuBtn).m -tearoff 0]\n\
$data(typeMenuBtn) config -takefocus 1 -highlightthickness 2 \\\n\
-relief raised -bd 2 -anchor w\n\
set data(okBtn)     [button $f2.ok     -text OK     -under 0 -width 6 \\\n\
-default active -pady 3]\n\
set data(cancelBtn) [button $f3.cancel -text Cancel -under 0 -width 6\\\n\
-default normal -pady 3]\n\
pack $data(okBtn) -side right -padx 4 -anchor e\n\
pack $f2.lab -side left -padx 4\n\
pack $f2.ent -expand yes -fill x -padx 2 -pady 0\n\
pack $data(cancelBtn) -side right -padx 4 -anchor w\n\
pack $data(typeMenuLab) -side left -padx 4\n\
pack $data(typeMenuBtn) -expand yes -fill x -side right\n\
pack $f1 -side top -fill x -pady 4\n\
pack $f3 -side bottom -fill x\n\
pack $f2 -side bottom -fill x\n\
pack $data(icons) -expand yes -fill both -padx 4 -pady 1\n\
bind $data(ent) <Return>  \"tkFDialog_ActivateEnt $w\"\n\
$data(upBtn)     config -command \"tkFDialog_UpDirCmd $w\"\n\
$data(okBtn)     config -command \"tkFDialog_OkCmd $w\"\n\
$data(cancelBtn) config -command \"tkFDialog_CancelCmd $w\"\n\
trace variable data(selectPath) w \"tkFDialog_SetPath $w\"\n\
bind $w <Alt-d> \"focus $data(dirMenuBtn)\"\n\
bind $w <Alt-t> [format {\n\
if {\"[%s cget -state]\" == \"normal\"} {\n\
focus %s\n\
}\n\
} $data(typeMenuBtn) $data(typeMenuBtn)]\n\
bind $w <Alt-n> \"focus $data(ent)\"\n\
bind $w <KeyPress-Escape> \"tkButtonInvoke $data(cancelBtn)\"\n\
bind $w <Alt-c> \"tkButtonInvoke $data(cancelBtn)\"\n\
bind $w <Alt-o> \"tkFDialog_InvokeBtn $w Open\"\n\
bind $w <Alt-s> \"tkFDialog_InvokeBtn $w Save\"\n\
wm protocol $w WM_DELETE_WINDOW \"tkFDialog_CancelCmd $w\"\n\
tkFocusGroup_Create $w\n\
tkFocusGroup_BindIn $w  $data(ent) \"tkFDialog_EntFocusIn $w\"\n\
tkFocusGroup_BindOut $w $data(ent) \"tkFDialog_EntFocusOut $w\"\n\
}\n\
proc tkFDialog_UpdateWhenIdle {w} {\n\
upvar #0 [winfo name $w] data\n\
if {[info exists data(updateId)]} {\n\
return\n\
} else {\n\
set data(updateId) [after idle tkFDialog_Update $w]\n\
}\n\
}\n\
proc tkFDialog_Update {w} {\n\
if {![winfo exists $w] || [string compare [winfo class $w] TkFDialog]} {\n\
return\n\
}\n\
set dataName [winfo name $w]\n\
upvar #0 $dataName data\n\
global tk_library tkPriv\n\
catch {unset data(updateId)}\n\
if {![info exists tkPriv(folderImage)]} {\n\
set tkPriv(folderImage) [image create photo -data {\n\
R0lGODlhEAAMAKEAAAD//wAAAPD/gAAAACH5BAEAAAAALAAAAAAQAAwAAAIghINhyycvVFsB\n\
QtmS3rjaH1Hg141WaT5ouprt2HHcUgAAOw==}]\n\
set tkPriv(fileImage)   [image create photo -data {\n\
R0lGODlhDAAMAKEAALLA3AAAAP//8wAAACH5BAEAAAAALAAAAAAMAAwAAAIgRI4Ha+IfWHsO\n\
rSASvJTGhnhcV3EJlo3kh53ltF5nAhQAOw==}]\n\
}\n\
set folder $tkPriv(folderImage)\n\
set file   $tkPriv(fileImage)\n\
set appPWD [pwd]\n\
if {[catch {\n\
cd $data(selectPath)\n\
}]} {\n\
tk_messageBox -type ok -parent $data(-parent) -message \\\n\
\"Cannot change to the directory \\\"$data(selectPath)\\\".\\nPermission denied.\"\\\n\
-icon warning\n\
cd $appPWD\n\
return\n\
}\n\
set entCursor [$data(ent) cget -cursor]\n\
set dlgCursor [$w         cget -cursor]\n\
$data(ent) config -cursor watch\n\
$w         config -cursor watch\n\
update idletasks\n\
tkIconList_DeleteAll $data(icons)\n\
foreach f [lsort -dictionary [glob -nocomplain .* *]] {\n\
if {![string compare $f .]} {\n\
continue\n\
}\n\
if {![string compare $f ..]} {\n\
continue\n\
}\n\
if {[file isdir ./$f]} {\n\
if {![info exists hasDoneDir($f)]} {\n\
tkIconList_Add $data(icons) $folder $f\n\
set hasDoneDir($f) 1\n\
}\n\
}\n\
}\n\
if {![string compare $data(filter) *]} {\n\
set files [lsort -dictionary \\\n\
[glob -nocomplain .* *]]\n\
} else {\n\
set files [lsort -dictionary \\\n\
[eval glob -nocomplain $data(filter)]]\n\
}\n\
set top 0\n\
foreach f $files {\n\
if {![file isdir ./$f]} {\n\
if {![info exists hasDoneFile($f)]} {\n\
tkIconList_Add $data(icons) $file $f\n\
set hasDoneFile($f) 1\n\
}\n\
}\n\
}\n\
tkIconList_Arrange $data(icons)\n\
set list \"\"\n\
set dir \"\"\n\
foreach subdir [file split $data(selectPath)] {\n\
set dir [file join $dir $subdir]\n\
lappend list $dir\n\
}\n\
$data(dirMenu) delete 0 end\n\
set var [format %s(selectPath) $dataName]\n\
foreach path $list {\n\
$data(dirMenu) add command -label $path -command [list set $var $path]\n\
}\n\
cd $appPWD\n\
$data(ent) config -cursor $entCursor\n\
$w         config -cursor $dlgCursor\n\
}\n\
proc tkFDialog_SetPathSilently {w path} {\n\
upvar #0 [winfo name $w] data\n\
trace vdelete  data(selectPath) w \"tkFDialog_SetPath $w\"\n\
set data(selectPath) $path\n\
trace variable data(selectPath) w \"tkFDialog_SetPath $w\"\n\
}\n\
proc tkFDialog_SetPath {w name1 name2 op} {\n\
if {[winfo exists $w]} {\n\
upvar #0 [winfo name $w] data\n\
tkFDialog_UpdateWhenIdle $w\n\
}\n\
}\n\
proc tkFDialog_SetFilter {w type} {\n\
upvar #0 [winfo name $w] data\n\
upvar \\#0 $data(icons) icons\n\
set data(filter) [lindex $type 1]\n\
$data(typeMenuBtn) config -text [lindex $type 0] -indicatoron 1\n\
$icons(sbar) set 0.0 0.0\n\
tkFDialog_UpdateWhenIdle $w\n\
}\n\
proc tkFDialogResolveFile {context text defaultext} {\n\
set appPWD [pwd]\n\
set path [tkFDialog_JoinFile $context $text]\n\
if {[file ext $path] == \"\"} {\n\
set path \"$path$defaultext\"\n\
}\n\
if {[catch {file exists $path}]} {\n\
return [list ERROR $path \"\"]\n\
}\n\
if {[file exists $path]} {\n\
if {[file isdirectory $path]} {\n\
if {[catch {\n\
cd $path\n\
}]} {\n\
return [list CHDIR $path \"\"]\n\
}\n\
set directory [pwd]\n\
set file \"\"\n\
set flag OK\n\
cd $appPWD\n\
} else {\n\
if {[catch {\n\
cd [file dirname $path]\n\
}]} {\n\
return [list CHDIR [file dirname $path] \"\"]\n\
}\n\
set directory [pwd]\n\
set file [file tail $path]\n\
set flag OK\n\
cd $appPWD\n\
}\n\
} else {\n\
set dirname [file dirname $path]\n\
if {[file exists $dirname]} {\n\
if {[catch {\n\
cd $dirname\n\
}]} {\n\
return [list CHDIR $dirname \"\"]\n\
}\n\
set directory [pwd]\n\
set file [file tail $path]\n\
if {[regexp {[*]|[?]} $file]} {\n\
set flag PATTERN\n\
} else {\n\
set flag FILE\n\
}\n\
cd $appPWD\n\
} else {\n\
set directory $dirname\n\
set file [file tail $path]\n\
set flag PATH\n\
}\n\
}\n\
return [list $flag $directory $file]\n\
}\n\
proc tkFDialog_EntFocusIn {w} {\n\
upvar #0 [winfo name $w] data\n\
if {[string compare [$data(ent) get] \"\"]} {\n\
$data(ent) selection from 0\n\
$data(ent) selection to   end\n\
$data(ent) icursor end\n\
} else {\n\
$data(ent) selection clear\n\
}\n\
tkIconList_Unselect $data(icons)\n\
if {![string compare $data(type) open]} {\n\
$data(okBtn) config -text \"Open\"\n\
} else {\n\
$data(okBtn) config -text \"Save\"\n\
}\n\
}\n\
proc tkFDialog_EntFocusOut {w} {\n\
upvar #0 [winfo name $w] data\n\
$data(ent) selection clear\n\
}\n\
proc tkFDialog_ActivateEnt {w} {\n\
upvar #0 [winfo name $w] data\n\
set text [string trim [$data(ent) get]]\n\
set list [tkFDialogResolveFile $data(selectPath) $text \\\n\
$data(-defaultextension)]\n\
set flag [lindex $list 0]\n\
set path [lindex $list 1]\n\
set file [lindex $list 2]\n\
case $flag {\n\
OK {\n\
if {![string compare $file \"\"]} {\n\
set data(selectPath) $path\n\
$data(ent) delete 0 end\n\
} else {\n\
tkFDialog_SetPathSilently $w $path\n\
set data(selectFile) $file\n\
tkFDialog_Done $w\n\
}\n\
}\n\
PATTERN {\n\
set data(selectPath) $path\n\
set data(filter) $file\n\
}\n\
FILE {\n\
if {![string compare $data(type) open]} {\n\
tk_messageBox -icon warning -type ok -parent $data(-parent) \\\n\
-message \"File \\\"[file join $path $file]\\\" does not exist.\"\n\
$data(ent) select from 0\n\
$data(ent) select to   end\n\
$data(ent) icursor end\n\
} else {\n\
tkFDialog_SetPathSilently $w $path\n\
set data(selectFile) $file\n\
tkFDialog_Done $w\n\
}\n\
}\n\
PATH {\n\
tk_messageBox -icon warning -type ok -parent $data(-parent) \\\n\
-message \"Directory \\\"$path\\\" does not exist.\"\n\
$data(ent) select from 0\n\
$data(ent) select to   end\n\
$data(ent) icursor end\n\
}\n\
CHDIR {\n\
tk_messageBox -type ok -parent $data(-parent) -message \\\n\
\"Cannot change to the directory \\\"$path\\\".\\nPermission denied.\"\\\n\
-icon warning\n\
$data(ent) select from 0\n\
$data(ent) select to   end\n\
$data(ent) icursor end\n\
}\n\
ERROR {\n\
tk_messageBox -type ok -parent $data(-parent) -message \\\n\
\"Invalid file name \\\"$path\\\".\"\\\n\
-icon warning\n\
$data(ent) select from 0\n\
$data(ent) select to   end\n\
$data(ent) icursor end\n\
}\n\
}\n\
}\n\
proc tkFDialog_InvokeBtn {w key} {\n\
upvar #0 [winfo name $w] data\n\
if {![string compare [$data(okBtn) cget -text] $key]} {\n\
tkButtonInvoke $data(okBtn)\n\
}\n\
}\n\
proc tkFDialog_UpDirCmd {w} {\n\
upvar #0 [winfo name $w] data\n\
if {[string compare $data(selectPath) \"/\"]} {\n\
set data(selectPath) [file dirname $data(selectPath)]\n\
}\n\
}\n\
proc tkFDialog_JoinFile {path file} {\n\
if {[string match {~*} $file] && [file exists $path/$file]} {\n\
return [file join $path ./$file]\n\
} else {\n\
return [file join $path $file]\n\
}\n\
}\n\
proc tkFDialog_OkCmd {w} {\n\
upvar #0 [winfo name $w] data\n\
set text [tkIconList_Get $data(icons)]\n\
if {[string compare $text \"\"]} {\n\
set file [tkFDialog_JoinFile $data(selectPath) $text]\n\
if {[file isdirectory $file]} {\n\
tkFDialog_ListInvoke $w $text\n\
return\n\
}\n\
}\n\
tkFDialog_ActivateEnt $w\n\
}\n\
proc tkFDialog_CancelCmd {w} {\n\
upvar #0 [winfo name $w] data\n\
global tkPriv\n\
set tkPriv(selectFilePath) \"\"\n\
}\n\
proc tkFDialog_ListBrowse {w text} {\n\
upvar #0 [winfo name $w] data\n\
if {$text == \"\"} {\n\
return\n\
}\n\
set file [tkFDialog_JoinFile $data(selectPath) $text]\n\
if {![file isdirectory $file]} {\n\
$data(ent) delete 0 end\n\
$data(ent) insert 0 $text\n\
if {![string compare $data(type) open]} {\n\
$data(okBtn) config -text \"Open\"\n\
} else {\n\
$data(okBtn) config -text \"Save\"\n\
}\n\
} else {\n\
$data(okBtn) config -text \"Open\"\n\
}\n\
}\n\
proc tkFDialog_ListInvoke {w text} {\n\
upvar #0 [winfo name $w] data\n\
if {$text == \"\"} {\n\
return\n\
}\n\
set file [tkFDialog_JoinFile $data(selectPath) $text]\n\
if {[file isdirectory $file]} {\n\
set appPWD [pwd]\n\
if {[catch {cd $file}]} {\n\
tk_messageBox -type ok -parent $data(-parent) -message \\\n\
\"Cannot change to the directory \\\"$file\\\".\\nPermission denied.\"\\\n\
-icon warning\n\
} else {\n\
cd $appPWD\n\
set data(selectPath) $file\n\
}\n\
} else {\n\
set data(selectFile) $file\n\
tkFDialog_Done $w\n\
}\n\
}\n\
proc tkFDialog_Done {w {selectFilePath \"\"}} {\n\
upvar #0 [winfo name $w] data\n\
global tkPriv\n\
if {![string compare $selectFilePath \"\"]} {\n\
set selectFilePath [tkFDialog_JoinFile $data(selectPath) \\\n\
$data(selectFile)]\n\
set tkPriv(selectFile)     $data(selectFile)\n\
set tkPriv(selectPath)     $data(selectPath)\n\
if {[file exists $selectFilePath] && \n\
![string compare $data(type) save]} {\n\
set reply [tk_messageBox -icon warning -type yesno\\\n\
-parent $data(-parent) -message \"File\\\n\
\\\"$selectFilePath\\\" already exists.\\nDo\\\n\
you want to overwrite it?\"]\n\
if {![string compare $reply \"no\"]} {\n\
return\n\
}\n\
}\n\
}\n\
set tkPriv(selectFilePath) $selectFilePath\n\
}\n\
";
