/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_console[] = "\
proc tkConsoleInit {} {\n\
global tcl_platform\n\
if {! [consoleinterp eval {set tcl_interactive}]} {\n\
wm withdraw .\n\
}\n\
if {\"$tcl_platform(platform)\" == \"macintosh\"} {\n\
set mod \"Cmd\"\n\
} else {\n\
set mod \"Ctrl\"\n\
}\n\
menu .menubar\n\
.menubar add cascade -label File -menu .menubar.file -underline 0\n\
.menubar add cascade -label Edit -menu .menubar.edit -underline 0\n\
menu .menubar.file -tearoff 0\n\
.menubar.file add command -label \"Source...\" -underline 0 \\\n\
-command tkConsoleSource\n\
.menubar.file add command -label \"Hide Console\" -underline 0 \\\n\
-command {wm withdraw .}\n\
if {\"$tcl_platform(platform)\" == \"macintosh\"} {\n\
.menubar.file add command -label \"Quit\" -command exit -accel Cmd-Q\n\
} else {\n\
.menubar.file add command -label \"Exit\" -underline 1 -command exit\n\
}\n\
menu .menubar.edit -tearoff 0\n\
.menubar.edit add command -label \"Cut\" -underline 2 \\\n\
-command { event generate .console <<Cut>> } -accel \"$mod+X\"\n\
.menubar.edit add command -label \"Copy\" -underline 0 \\\n\
-command { event generate .console <<Copy>> } -accel \"$mod+C\"\n\
.menubar.edit add command -label \"Paste\" -underline 1 \\\n\
-command { event generate .console <<Paste>> } -accel \"$mod+V\"\n\
if {\"$tcl_platform(platform)\" == \"windows\"} {\n\
.menubar.edit add command -label \"Delete\" -underline 0 \\\n\
-command { event generate .console <<Clear>> } -accel \"Del\"\n\
.menubar add cascade -label Help -menu .menubar.help -underline 0\n\
menu .menubar.help -tearoff 0\n\
.menubar.help add command -label \"About...\" -underline 0 \\\n\
-command tkConsoleAbout\n\
} else {\n\
.menubar.edit add command -label \"Clear\" -underline 2 \\\n\
-command { event generate .console <<Clear>> }\n\
}\n\
. conf -menu .menubar\n\
text .console  -yscrollcommand \".sb set\" -setgrid true \n\
scrollbar .sb -command \".console yview\"\n\
pack .sb -side right -fill both\n\
pack .console -fill both -expand 1 -side left\n\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
.console configure -font {Monaco 9 normal} -highlightthickness 0\n\
}\n\
tkConsoleBind .console\n\
.console tag configure stderr -foreground red\n\
.console tag configure stdin -foreground blue\n\
focus .console\n\
wm protocol . WM_DELETE_WINDOW { wm withdraw . }\n\
wm title . \"Console\"\n\
flush stdout\n\
.console mark set output [.console index \"end - 1 char\"]\n\
tkTextSetCursor .console end\n\
.console mark set promptEnd insert\n\
.console mark gravity promptEnd left\n\
}\n\
proc tkConsoleSource {} {\n\
set filename [tk_getOpenFile -defaultextension .tcl -parent . \\\n\
-title \"Select a file to source\" \\\n\
-filetypes {{\"Tcl Scripts\" .tcl} {\"All Files\" *}}]\n\
if {\"$filename\" != \"\"} {\n\
set cmd [list source $filename]\n\
if {[catch {consoleinterp eval $cmd} result]} {\n\
tkConsoleOutput stderr \"$result\\n\"\n\
}\n\
}\n\
}\n\
proc tkConsoleInvoke {args} {\n\
set ranges [.console tag ranges input]\n\
set cmd \"\"\n\
if {$ranges != \"\"} {\n\
set pos 0\n\
while {[lindex $ranges $pos] != \"\"} {\n\
set start [lindex $ranges $pos]\n\
set end [lindex $ranges [incr pos]]\n\
append cmd [.console get $start $end]\n\
incr pos\n\
}\n\
}\n\
if {$cmd == \"\"} {\n\
tkConsolePrompt\n\
} elseif {[info complete $cmd]} {\n\
.console mark set output end\n\
.console tag delete input\n\
set result [consoleinterp record $cmd]\n\
if {$result != \"\"} {\n\
.console insert insert \"$result\\n\"\n\
}\n\
tkConsoleHistory reset\n\
tkConsolePrompt\n\
} else {\n\
tkConsolePrompt partial\n\
}\n\
.console yview -pickplace insert\n\
}\n\
set histNum 1\n\
proc tkConsoleHistory {cmd} {\n\
global histNum\n\
switch $cmd {\n\
prev {\n\
incr histNum -1\n\
if {$histNum == 0} {\n\
set cmd {history event [expr {[history nextid] -1}]}\n\
} else {\n\
set cmd \"history event $histNum\"\n\
}\n\
if {[catch {consoleinterp eval $cmd} cmd]} {\n\
incr histNum\n\
return\n\
}\n\
.console delete promptEnd end\n\
.console insert promptEnd $cmd {input stdin}\n\
}\n\
next {\n\
incr histNum\n\
if {$histNum == 0} {\n\
set cmd {history event [expr {[history nextid] -1}]}\n\
} elseif {$histNum > 0} {\n\
set cmd \"\"\n\
set histNum 1\n\
} else {\n\
set cmd \"history event $histNum\"\n\
}\n\
if {$cmd != \"\"} {\n\
catch {consoleinterp eval $cmd} cmd\n\
}\n\
.console delete promptEnd end\n\
.console insert promptEnd $cmd {input stdin}\n\
}\n\
reset {\n\
set histNum 1\n\
}\n\
}\n\
}\n\
proc tkConsolePrompt {{partial normal}} {\n\
if {$partial == \"normal\"} {\n\
set temp [.console index \"end - 1 char\"]\n\
.console mark set output end\n\
if {[consoleinterp eval \"info exists tcl_prompt1\"]} {\n\
consoleinterp eval \"eval \\[set tcl_prompt1\\]\"\n\
} else {\n\
puts -nonewline \"% \"\n\
}\n\
} else {\n\
set temp [.console index output]\n\
.console mark set output end\n\
if {[consoleinterp eval \"info exists tcl_prompt2\"]} {\n\
consoleinterp eval \"eval \\[set tcl_prompt2\\]\"\n\
} else {\n\
puts -nonewline \"> \"\n\
}\n\
}\n\
flush stdout\n\
.console mark set output $temp\n\
tkTextSetCursor .console end\n\
.console mark set promptEnd insert\n\
.console mark gravity promptEnd left\n\
}\n\
proc tkConsoleBind {win} {\n\
bindtags $win \"$win Text . all\"\n\
bind $win <Alt-KeyPress> {# nothing }\n\
bind $win <Meta-KeyPress> {# nothing}\n\
bind $win <Control-KeyPress> {# nothing}\n\
bind $win <Escape> {# nothing}\n\
bind $win <KP_Enter> {# nothing}\n\
bind $win <Tab> {\n\
tkConsoleInsert %W \\t\n\
focus %W\n\
break\n\
}\n\
bind $win <Return> {\n\
%W mark set insert {end - 1c}\n\
tkConsoleInsert %W \"\\n\"\n\
tkConsoleInvoke\n\
break\n\
}\n\
bind $win <Delete> {\n\
if {[%W tag nextrange sel 1.0 end] != \"\"} {\n\
%W tag remove sel sel.first promptEnd\n\
} else {\n\
if {[%W compare insert < promptEnd]} {\n\
break\n\
}\n\
}\n\
}\n\
bind $win <BackSpace> {\n\
if {[%W tag nextrange sel 1.0 end] != \"\"} {\n\
%W tag remove sel sel.first promptEnd\n\
} else {\n\
if {[%W compare insert <= promptEnd]} {\n\
break\n\
}\n\
}\n\
}\n\
foreach left {Control-a Home} {\n\
bind $win <$left> {\n\
if {[%W compare insert < promptEnd]} {\n\
tkTextSetCursor %W {insert linestart}\n\
} else {\n\
tkTextSetCursor %W promptEnd\n\
}\n\
break\n\
}\n\
}\n\
foreach right {Control-e End} {\n\
bind $win <$right> {\n\
tkTextSetCursor %W {insert lineend}\n\
break\n\
}\n\
}\n\
bind $win <Control-d> {\n\
if {[%W compare insert < promptEnd]} {\n\
break\n\
}\n\
}\n\
bind $win <Control-k> {\n\
if {[%W compare insert < promptEnd]} {\n\
%W mark set insert promptEnd\n\
}\n\
}\n\
bind $win <Control-t> {\n\
if {[%W compare insert < promptEnd]} {\n\
break\n\
}\n\
}\n\
bind $win <Meta-d> {\n\
if {[%W compare insert < promptEnd]} {\n\
break\n\
}\n\
}\n\
bind $win <Meta-BackSpace> {\n\
if {[%W compare insert <= promptEnd]} {\n\
break\n\
}\n\
}\n\
bind $win <Control-h> {\n\
if {[%W compare insert <= promptEnd]} {\n\
break\n\
}\n\
}\n\
foreach prev {Control-p Up} {\n\
bind $win <$prev> {\n\
tkConsoleHistory prev\n\
break\n\
}\n\
}\n\
foreach prev {Control-n Down} {\n\
bind $win <$prev> {\n\
tkConsoleHistory next\n\
break\n\
}\n\
}\n\
bind $win <Insert> {\n\
catch {tkConsoleInsert %W [selection get -displayof %W]}\n\
break\n\
}\n\
bind $win <KeyPress> {\n\
tkConsoleInsert %W %A\n\
break\n\
}\n\
foreach left {Control-b Left} {\n\
bind $win <$left> {\n\
if {[%W compare insert == promptEnd]} {\n\
break\n\
}\n\
tkTextSetCursor %W insert-1c\n\
break\n\
}\n\
}\n\
foreach right {Control-f Right} {\n\
bind $win <$right> {\n\
tkTextSetCursor %W insert+1c\n\
break\n\
}\n\
}\n\
bind $win <F9> {\n\
eval destroy [winfo child .]\n\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
source -rsrc Console\n\
} else {\n\
source [file join $tk_library console.tcl]\n\
}\n\
}\n\
bind $win <<Cut>> {\n\
if {![catch {set data [%W get sel.first sel.last]}]} {\n\
clipboard clear -displayof %W\n\
clipboard append -displayof %W $data\n\
}\n\
break\n\
}\n\
bind $win <<Copy>> {\n\
if {![catch {set data [%W get sel.first sel.last]}]} {\n\
clipboard clear -displayof %W\n\
clipboard append -displayof %W $data\n\
}\n\
break\n\
}\n\
bind $win <<Paste>> {\n\
catch {\n\
set clip [selection get -displayof %W -selection CLIPBOARD]\n\
set list [split $clip \\n\\r]\n\
tkConsoleInsert %W [lindex $list 0]\n\
foreach x [lrange $list 1 end] {\n\
%W mark set insert {end - 1c}\n\
tkConsoleInsert %W \"\\n\"\n\
tkConsoleInvoke\n\
tkConsoleInsert %W $x\n\
}\n\
}\n\
break\n\
}\n\
}\n\
proc tkConsoleInsert {w s} {\n\
if {$s == \"\"} {\n\
return\n\
}\n\
catch {\n\
if {[$w compare sel.first <= insert]\n\
&& [$w compare sel.last >= insert]} {\n\
$w tag remove sel sel.first promptEnd\n\
$w delete sel.first sel.last\n\
}\n\
}\n\
if {[$w compare insert < promptEnd]} {\n\
$w mark set insert end	\n\
}\n\
$w insert insert $s {input stdin}\n\
$w see insert\n\
}\n\
proc tkConsoleOutput {dest string} {\n\
.console insert output $string $dest\n\
.console see insert\n\
}\n\
proc tkConsoleExit {} {\n\
destroy .\n\
}\n\
proc tkConsoleAbout {} {\n\
global tk_patchLevel\n\
tk_messageBox -type ok -message \"Tcl for Windows\n\
Copyright \\251 1996 Sun Microsystems, Inc.\n\
Tcl [info patchlevel]\n\
Tk $tk_patchLevel\"\n\
}\n\
tkConsoleInit\n\
";
