/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_bgerror[] = "\
proc bgerror err {\n\
global errorInfo tcl_platform\n\
set info $errorInfo ;\n\
set ret [catch {tkerror $err} msg];\n\
if {$ret != 1} {return -code $ret $msg}\n\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
set ok Ok\n\
} else {\n\
set ok OK\n\
}\n\
set button [tk_dialog .bgerrorDialog \"Error in Tcl Script\" \\\n\
\"Error: $err\" error 0 $ok \"Skip Messages\" \"Stack Trace\"]\n\
if {$button == 0} {\n\
return\n\
} elseif {$button == 1} {\n\
return -code break\n\
}\n\
set w .bgerrorTrace\n\
catch {destroy $w}\n\
toplevel $w -class ErrorTrace\n\
wm minsize $w 1 1\n\
wm title $w \"Stack Trace for Error\"\n\
wm iconname $w \"Stack Trace\"\n\
button $w.ok -text OK -command \"destroy $w\" -default active\n\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
text $w.text -relief flat -bd 2 -highlightthickness 0 -setgrid true \\\n\
-yscrollcommand \"$w.scroll set\" -width 60 -height 20\n\
} else {\n\
text $w.text -relief sunken -bd 2 -yscrollcommand \"$w.scroll set\" \\\n\
-setgrid true -width 60 -height 20\n\
}\n\
scrollbar $w.scroll -relief sunken -command \"$w.text yview\"\n\
pack $w.ok -side bottom -padx 3m -pady 2m\n\
pack $w.scroll -side right -fill y\n\
pack $w.text -side left -expand yes -fill both\n\
$w.text insert 0.0 $info\n\
$w.text mark set insert 0.0\n\
bind $w <Return> \"destroy $w\"\n\
bind $w.text <Return> \"destroy $w; break\"\n\
wm withdraw $w\n\
update idletasks\n\
set x [expr {[winfo screenwidth $w]/2 - [winfo reqwidth $w]/2 \\\n\
- [winfo vrootx [winfo parent $w]]}]\n\
set y [expr {[winfo screenheight $w]/2 - [winfo reqheight $w]/2 \\\n\
- [winfo vrooty [winfo parent $w]]}]\n\
wm geom $w +$x+$y\n\
wm deiconify $w\n\
if {[grab current .] != \"\"} {\n\
grab release [grab current .]\n\
}\n\
}\n\
";
