/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_clrpick[] = "\
proc tkColorDialog {args} {\n\
global tkPriv\n\
set w .__tk__color\n\
upvar #0 $w data\n\
set data(lines,red,start)   0\n\
set data(lines,red,last)   -1\n\
set data(lines,green,start) 0\n\
set data(lines,green,last) -1\n\
set data(lines,blue,start)  0\n\
set data(lines,blue,last)  -1\n\
set data(NUM_COLORBARS) 8\n\
set data(BARS_WIDTH) 128\n\
set data(PLGN_HEIGHT) 10\n\
set data(PLGN_WIDTH) 10\n\
tkColorDialog_Config $w $args\n\
tkColorDialog_InitValues $w\n\
if {![winfo exists $w]} {\n\
toplevel $w -class tkColorDialog\n\
tkColorDialog_BuildDialog $w\n\
}\n\
wm transient $w $data(-parent)\n\
wm withdraw $w\n\
update idletasks\n\
set x [expr {[winfo screenwidth $w]/2 - [winfo reqwidth $w]/2 \\\n\
- [winfo vrootx [winfo parent $w]]}]\n\
set y [expr {[winfo screenheight $w]/2 - [winfo reqheight $w]/2 \\\n\
- [winfo vrooty [winfo parent $w]]}]\n\
wm geom $w +$x+$y\n\
wm deiconify $w\n\
wm title $w $data(-title)\n\
set oldFocus [focus]\n\
set oldGrab [grab current $w]\n\
if {$oldGrab != \"\"} {\n\
set grabStatus [grab status $oldGrab]\n\
}\n\
grab $w\n\
focus $data(okBtn)\n\
tkwait variable tkPriv(selectColor)\n\
catch {focus $oldFocus}\n\
grab release $w\n\
destroy $w\n\
unset data\n\
if {$oldGrab != \"\"} {\n\
if {$grabStatus == \"global\"} {\n\
grab -global $oldGrab\n\
} else {\n\
grab $oldGrab\n\
}\n\
}\n\
return $tkPriv(selectColor)\n\
}\n\
proc tkColorDialog_InitValues {w} {\n\
upvar #0 $w data\n\
set data(intensityIncr) [expr {256 / $data(NUM_COLORBARS)}]\n\
set data(colorbarWidth) \\\n\
[expr {$data(BARS_WIDTH) / $data(NUM_COLORBARS)}]\n\
set data(indent) [expr {$data(PLGN_WIDTH) / 2}]\n\
set data(colorPad) 2\n\
set data(selPad)   [expr {$data(PLGN_WIDTH) / 2}]\n\
set data(minX) $data(indent)\n\
set data(maxX) [expr {$data(BARS_WIDTH) + $data(indent)-1}]\n\
set data(canvasWidth) [expr {$data(BARS_WIDTH) + \\\n\
$data(PLGN_WIDTH)}]\n\
set data(selection) $data(-initialcolor)\n\
set data(finalColor)  $data(-initialcolor)\n\
set rgb [winfo rgb . $data(selection)]\n\
set data(red,intensity)   [expr {[lindex $rgb 0]/0x100}]\n\
set data(green,intensity) [expr {[lindex $rgb 1]/0x100}]\n\
set data(blue,intensity)  [expr {[lindex $rgb 2]/0x100}]\n\
}\n\
proc tkColorDialog_Config {w argList} {\n\
global tkPriv\n\
upvar #0 $w data\n\
set specs {\n\
{-initialcolor \"\" \"\" \"\"}\n\
{-parent \"\" \"\" \".\"}\n\
{-title \"\" \"\" \"Color\"}\n\
}\n\
tclParseConfigSpec $w $specs \"\" $argList\n\
if {![string compare $data(-title) \"\"]} {\n\
set data(-title) \" \"\n\
}\n\
if {![string compare $data(-initialcolor) \"\"]} {\n\
if {[info exists tkPriv(selectColor)] && \\\n\
[string compare $tkPriv(selectColor) \"\"]} {\n\
set data(-initialcolor) $tkPriv(selectColor)\n\
} else {\n\
set data(-initialcolor) [. cget -background]\n\
}\n\
} else {\n\
if {[catch {winfo rgb . $data(-initialcolor)} err]} {\n\
error $err\n\
}\n\
}\n\
if {![winfo exists $data(-parent)]} {\n\
error \"bad window path name \\\"$data(-parent)\\\"\"\n\
}\n\
}\n\
proc tkColorDialog_BuildDialog {w} {\n\
upvar #0 $w data\n\
set topFrame [frame $w.top -relief raised -bd 1]\n\
set stripsFrame [frame $topFrame.colorStrip]\n\
foreach c { Red Green Blue } {\n\
set color [string tolower $c]\n\
set f [frame $stripsFrame.$color]\n\
set box [frame $f.box]\n\
label $box.label -text $c: -width 6 -under 0 -anchor ne\n\
entry $box.entry -textvariable [format %s $w]($color,intensity) \\\n\
-width 4\n\
pack $box.label -side left -fill y -padx 2 -pady 3\n\
pack $box.entry -side left -anchor n -pady 0\n\
pack $box -side left -fill both\n\
set height [expr \\\n\
{[winfo reqheight $box.entry] - \\\n\
2*([$box.entry cget -highlightthickness] + [$box.entry cget -bd])}]\n\
canvas $f.color -height $height\\\n\
-width $data(BARS_WIDTH) -relief sunken -bd 2\n\
canvas $f.sel -height $data(PLGN_HEIGHT) \\\n\
-width $data(canvasWidth) -highlightthickness 0\n\
pack $f.color -expand yes -fill both\n\
pack $f.sel -expand yes -fill both\n\
pack $f -side top -fill x -padx 0 -pady 2\n\
set data($color,entry) $box.entry\n\
set data($color,col) $f.color\n\
set data($color,sel) $f.sel\n\
bind $data($color,col) <Configure> \\\n\
\"tkColorDialog_DrawColorScale $w $color 1\"\n\
bind $data($color,col) <Enter> \\\n\
\"tkColorDialog_EnterColorBar $w $color\"\n\
bind $data($color,col) <Leave> \\\n\
\"tkColorDialog_LeaveColorBar $w $color\"\n\
bind $data($color,sel) <Enter> \\\n\
\"tkColorDialog_EnterColorBar $w $color\"\n\
bind $data($color,sel) <Leave> \\\n\
\"tkColorDialog_LeaveColorBar $w $color\"\n\
bind $box.entry <Return> \"tkColorDialog_HandleRGBEntry $w\"\n\
}\n\
pack $stripsFrame -side left -fill both -padx 4 -pady 10\n\
set selFrame [frame $topFrame.sel]\n\
set lab [label $selFrame.lab -text \"Selection:\" -under 0 -anchor sw]\n\
set ent [entry $selFrame.ent -textvariable [format %s $w](selection) \\\n\
-width 16]\n\
set f1  [frame $selFrame.f1 -relief sunken -bd 2]\n\
set data(finalCanvas) [frame $f1.demo -bd 0 -width 100 -height 70]\n\
pack $lab $ent -side top -fill x -padx 4 -pady 2\n\
pack $f1 -expand yes -anchor nw -fill both -padx 6 -pady 10\n\
pack $data(finalCanvas) -expand yes -fill both\n\
bind $ent <Return> \"tkColorDialog_HandleSelEntry $w\"\n\
pack $selFrame -side left -fill none -anchor nw\n\
pack $topFrame -side top -expand yes -fill both -anchor nw\n\
set botFrame [frame $w.bot -relief raised -bd 1]\n\
button $botFrame.ok     -text OK            -width 8 -under 0 \\\n\
-command \"tkColorDialog_OkCmd $w\"\n\
button $botFrame.cancel -text Cancel        -width 8 -under 0 \\\n\
-command \"tkColorDialog_CancelCmd $w\"\n\
set data(okBtn)      $botFrame.ok\n\
set data(cancelBtn)  $botFrame.cancel\n\
pack $botFrame.ok $botFrame.cancel \\\n\
-padx 10 -pady 10 -expand yes -side left\n\
pack $botFrame -side bottom -fill x\n\
bind $w <Alt-r> \"focus $data(red,entry)\"\n\
bind $w <Alt-g> \"focus $data(green,entry)\"\n\
bind $w <Alt-b> \"focus $data(blue,entry)\"\n\
bind $w <Alt-s> \"focus $ent\"\n\
bind $w <KeyPress-Escape> \"tkButtonInvoke $data(cancelBtn)\"\n\
bind $w <Alt-c> \"tkButtonInvoke $data(cancelBtn)\"\n\
bind $w <Alt-o> \"tkButtonInvoke $data(okBtn)\"\n\
wm protocol $w WM_DELETE_WINDOW \"tkColorDialog_CancelCmd $w\"\n\
}\n\
proc tkColorDialog_SetRGBValue {w color} {\n\
upvar #0 $w data \n\
set data(red,intensity)   [lindex $color 0]\n\
set data(green,intensity) [lindex $color 1]\n\
set data(blue,intensity)  [lindex $color 2]\n\
tkColorDialog_RedrawColorBars $w all\n\
foreach color { red green blue } {\n\
set x [tkColorDialog_RgbToX $w $data($color,intensity)]\n\
tkColorDialog_MoveSelector $w $data($color,sel) $color $x 0\n\
}\n\
}\n\
proc tkColorDialog_XToRgb {w x} {\n\
upvar #0 $w data\n\
return [expr {($x * $data(intensityIncr))/ $data(colorbarWidth)}]\n\
}\n\
proc tkColorDialog_RgbToX {w color} {\n\
upvar #0 $w data\n\
return [expr {($color * $data(colorbarWidth)/ $data(intensityIncr))}]\n\
}\n\
proc tkColorDialog_DrawColorScale {w c {create 0}} {\n\
global lines\n\
upvar #0 $w data\n\
set col $data($c,col)\n\
set sel $data($c,sel)\n\
if {$create} {\n\
if { $data(lines,$c,last) > $data(lines,$c,start)} {\n\
for {set i $data(lines,$c,start)} \\\n\
{$i <= $data(lines,$c,last)} { incr i} {\n\
$sel delete $i\n\
}\n\
}\n\
if {[info exists data($c,index)]} {\n\
$sel delete $data($c,index)\n\
}\n\
tkColorDialog_CreateSelector $w $sel $c\n\
$sel bind $data($c,index) <ButtonPress-1> \\\n\
\"tkColorDialog_StartMove $w $sel $c %x $data(selPad) 1\"\n\
$sel bind $data($c,index) <B1-Motion> \\\n\
\"tkColorDialog_MoveSelector $w $sel $c %x $data(selPad)\"\n\
$sel bind $data($c,index) <ButtonRelease-1> \\\n\
\"tkColorDialog_ReleaseMouse $w $sel $c %x $data(selPad)\"\n\
set height [winfo height $col]\n\
set data($c,clickRegion) [$sel create rectangle 0 0 \\\n\
$data(canvasWidth) $height -fill {} -outline {}]\n\
bind $col <ButtonPress-1> \\\n\
\"tkColorDialog_StartMove $w $sel $c %x $data(colorPad)\"\n\
bind $col <B1-Motion> \\\n\
\"tkColorDialog_MoveSelector $w $sel $c %x $data(colorPad)\"\n\
bind $col <ButtonRelease-1> \\\n\
\"tkColorDialog_ReleaseMouse $w $sel $c %x $data(colorPad)\"\n\
$sel bind $data($c,clickRegion) <ButtonPress-1> \\\n\
\"tkColorDialog_StartMove $w $sel $c %x $data(selPad)\"\n\
$sel bind $data($c,clickRegion) <B1-Motion> \\\n\
\"tkColorDialog_MoveSelector $w $sel $c %x $data(selPad)\"\n\
$sel bind $data($c,clickRegion) <ButtonRelease-1> \\\n\
\"tkColorDialog_ReleaseMouse $w $sel $c %x $data(selPad)\"\n\
} else {\n\
set l $data(lines,$c,start)\n\
}\n\
set highlightW [expr \\\n\
{[$col cget -highlightthickness] + [$col cget -bd]}]\n\
for {set i 0} { $i < $data(NUM_COLORBARS)} { incr i} {\n\
set intensity [expr {$i * $data(intensityIncr)}]\n\
set startx [expr {$i * $data(colorbarWidth) + $highlightW}]\n\
if { $c == \"red\" } {\n\
set color [format \"#%02x%02x%02x\" \\\n\
$intensity \\\n\
$data(green,intensity) \\\n\
$data(blue,intensity)]\n\
} elseif { $c == \"green\" } {\n\
set color [format \"#%02x%02x%02x\" \\\n\
$data(red,intensity) \\\n\
$intensity \\\n\
$data(blue,intensity)]\n\
} else {\n\
set color [format \"#%02x%02x%02x\" \\\n\
$data(red,intensity) \\\n\
$data(green,intensity) \\\n\
$intensity]\n\
}\n\
if {$create} {\n\
set index [$col create rect $startx $highlightW \\\n\
[expr {$startx +$data(colorbarWidth)}] \\\n\
[expr {[winfo height $col] + $highlightW}]\\\n\
-fill $color -outline $color]\n\
} else {\n\
$col itemconf $l -fill $color -outline $color\n\
incr l\n\
}\n\
}\n\
$sel raise $data($c,index)\n\
if {$create} {\n\
set data(lines,$c,last) $index\n\
set data(lines,$c,start) [expr {$index - $data(NUM_COLORBARS) + 1}]\n\
}\n\
tkColorDialog_RedrawFinalColor $w\n\
}\n\
proc tkColorDialog_CreateSelector {w sel c } {\n\
upvar #0 $w data\n\
set data($c,index) [$sel create polygon \\\n\
0 $data(PLGN_HEIGHT) \\\n\
$data(PLGN_WIDTH) $data(PLGN_HEIGHT) \\\n\
$data(indent) 0]\n\
set data($c,x) [tkColorDialog_RgbToX $w $data($c,intensity)]\n\
$sel move $data($c,index) $data($c,x) 0\n\
}\n\
proc tkColorDialog_RedrawFinalColor {w} {\n\
upvar #0 $w data\n\
set color [format \"#%02x%02x%02x\" $data(red,intensity) \\\n\
$data(green,intensity) $data(blue,intensity)]\n\
$data(finalCanvas) conf -bg $color\n\
set data(finalColor) $color\n\
set data(selection) $color\n\
set data(finalRGB) [list \\\n\
$data(red,intensity) \\\n\
$data(green,intensity) \\\n\
$data(blue,intensity)]\n\
}\n\
proc tkColorDialog_RedrawColorBars {w colorChanged} {\n\
upvar #0 $w data\n\
switch $colorChanged {\n\
red { \n\
tkColorDialog_DrawColorScale $w green\n\
tkColorDialog_DrawColorScale $w blue\n\
}\n\
green {\n\
tkColorDialog_DrawColorScale $w red\n\
tkColorDialog_DrawColorScale $w blue\n\
}\n\
blue {\n\
tkColorDialog_DrawColorScale $w red\n\
tkColorDialog_DrawColorScale $w green\n\
}\n\
default {\n\
tkColorDialog_DrawColorScale $w red\n\
tkColorDialog_DrawColorScale $w green\n\
tkColorDialog_DrawColorScale $w blue\n\
}\n\
}\n\
tkColorDialog_RedrawFinalColor $w\n\
}\n\
proc tkColorDialog_StartMove {w sel color x delta {dontMove 0}} {\n\
upvar #0 $w data\n\
if {!$dontMove} {\n\
tkColorDialog_MoveSelector $w $sel $color $x $delta\n\
}\n\
}\n\
proc tkColorDialog_MoveSelector {w sel color x delta} {\n\
upvar #0 $w data\n\
incr x -$delta\n\
if { $x < 0 } {\n\
set x 0\n\
} elseif { $x >= $data(BARS_WIDTH)} {\n\
set x [expr {$data(BARS_WIDTH) - 1}]\n\
}\n\
set diff [expr {$x - $data($color,x)}]\n\
$sel move $data($color,index) $diff 0\n\
set data($color,x) [expr {$data($color,x) + $diff}]\n\
return $x\n\
}\n\
proc tkColorDialog_ReleaseMouse {w sel color x delta} {\n\
upvar #0 $w data \n\
set x [tkColorDialog_MoveSelector $w $sel $color $x $delta]\n\
set data($color,intensity) [tkColorDialog_XToRgb $w $x]\n\
tkColorDialog_RedrawColorBars $w $color\n\
}\n\
proc tkColorDialog_ResizeColorBars {w} {\n\
upvar #0 $w data\n\
if { ($data(BARS_WIDTH) < $data(NUM_COLORBARS)) || \n\
(($data(BARS_WIDTH) % $data(NUM_COLORBARS)) != 0)} {\n\
set data(BARS_WIDTH) $data(NUM_COLORBARS)\n\
}\n\
tkColorDialog_InitValues $w\n\
foreach color { red green blue } {\n\
$data($color,col) conf -width $data(canvasWidth)\n\
tkColorDialog_DrawColorScale $w $color 1\n\
}\n\
}\n\
proc tkColorDialog_HandleSelEntry {w} {\n\
upvar #0 $w data\n\
set text [string trim $data(selection)]\n\
if {[catch {set color [winfo rgb . $text]} ]} {\n\
set data(selection) $data(finalColor)\n\
return\n\
}\n\
set R [expr {[lindex $color 0]/0x100}]\n\
set G [expr {[lindex $color 1]/0x100}]\n\
set B [expr {[lindex $color 2]/0x100}]\n\
tkColorDialog_SetRGBValue $w \"$R $G $B\"\n\
set data(selection) $text\n\
}\n\
proc tkColorDialog_HandleRGBEntry {w} {\n\
upvar #0 $w data\n\
foreach c {red green blue} {\n\
if {[catch {\n\
set data($c,intensity) [expr {int($data($c,intensity))}]\n\
}]} {\n\
set data($c,intensity) 0\n\
}\n\
if {$data($c,intensity) < 0} {\n\
set data($c,intensity) 0\n\
}\n\
if {$data($c,intensity) > 255} {\n\
set data($c,intensity) 255\n\
}\n\
}\n\
tkColorDialog_SetRGBValue $w \"$data(red,intensity) $data(green,intensity) \\\n\
$data(blue,intensity)\"\n\
}    \n\
proc tkColorDialog_EnterColorBar {w color} {\n\
upvar #0 $w data\n\
$data($color,sel) itemconfig $data($color,index) -fill red\n\
}\n\
proc tkColorDialog_LeaveColorBar {w color} {\n\
upvar #0 $w data\n\
$data($color,sel) itemconfig $data($color,index) -fill black\n\
}\n\
proc tkColorDialog_OkCmd {w} {\n\
global tkPriv\n\
upvar #0 $w data\n\
set tkPriv(selectColor) $data(finalColor)\n\
}\n\
proc tkColorDialog_CancelCmd {w} {\n\
global tkPriv\n\
set tkPriv(selectColor) \"\"\n\
}\n\
";
