/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_msgbox[] = "\
proc tkMessageBox {args} {\n\
global tkPriv tcl_platform\n\
set w tkPrivMsgBox\n\
upvar #0 $w data\n\
set specs {\n\
{-default \"\" \"\" \"\"}\n\
{-icon \"\" \"\" \"info\"}\n\
{-message \"\" \"\" \"\"}\n\
{-parent \"\" \"\" .}\n\
{-title \"\" \"\" \" \"}\n\
{-type \"\" \"\" \"ok\"}\n\
}\n\
tclParseConfigSpec $w $specs \"\" $args\n\
if {[lsearch {info warning error question} $data(-icon)] == -1} {\n\
error \"invalid icon \\\"$data(-icon)\\\", must be error, info, question or warning\"\n\
}\n\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
if {$data(-icon) == \"error\"} {\n\
set data(-icon) \"stop\"\n\
} elseif {$data(-icon) == \"warning\"} {\n\
set data(-icon) \"caution\"\n\
} elseif {$data(-icon) == \"info\"} {\n\
set data(-icon) \"note\"\n\
}\n\
}\n\
if {![winfo exists $data(-parent)]} {\n\
error \"bad window path name \\\"$data(-parent)\\\"\"\n\
}\n\
case $data(-type) {\n\
abortretryignore {\n\
set buttons {\n\
{abort  -width 6 -text Abort -under 0}\n\
{retry  -width 6 -text Retry -under 0}\n\
{ignore -width 6 -text Ignore -under 0}\n\
}\n\
}\n\
ok {\n\
set buttons {\n\
{ok -width 6 -text OK -under 0}\n\
}\n\
if {$data(-default) == \"\"} {\n\
set data(-default) \"ok\"\n\
}\n\
}\n\
okcancel {\n\
set buttons {\n\
{ok     -width 6 -text OK     -under 0}\n\
{cancel -width 6 -text Cancel -under 0}\n\
}\n\
}\n\
retrycancel {\n\
set buttons {\n\
{retry  -width 6 -text Retry  -under 0}\n\
{cancel -width 6 -text Cancel -under 0}\n\
}\n\
}\n\
yesno {\n\
set buttons {\n\
{yes    -width 6 -text Yes -under 0}\n\
{no     -width 6 -text No  -under 0}\n\
}\n\
}\n\
yesnocancel {\n\
set buttons {\n\
{yes    -width 6 -text Yes -under 0}\n\
{no     -width 6 -text No  -under 0}\n\
{cancel -width 6 -text Cancel -under 0}\n\
}\n\
}\n\
default {\n\
error \"invalid message box type \\\"$data(-type)\\\", must be abortretryignore, ok, okcancel, retrycancel, yesno or yesnocancel\"\n\
}\n\
}\n\
if {[string compare $data(-default) \"\"]} {\n\
set valid 0\n\
foreach btn $buttons {\n\
if {![string compare [lindex $btn 0] $data(-default)]} {\n\
set valid 1\n\
break\n\
}\n\
}\n\
if {!$valid} {\n\
error \"invalid default button \\\"$data(-default)\\\"\"\n\
}\n\
}\n\
if {[string compare $data(-parent) .]} {\n\
set w $data(-parent).__tk__messagebox\n\
} else {\n\
set w .__tk__messagebox\n\
}\n\
catch {destroy $w}\n\
toplevel $w -class Dialog\n\
wm title $w $data(-title)\n\
wm iconname $w Dialog\n\
wm protocol $w WM_DELETE_WINDOW { }\n\
wm transient $w $data(-parent)\n\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
unsupported1 style $w dBoxProc\n\
}\n\
frame $w.bot\n\
pack $w.bot -side bottom -fill both\n\
frame $w.top\n\
pack $w.top -side top -fill both -expand 1\n\
if {$tcl_platform(platform) != \"macintosh\"} {\n\
$w.bot configure -relief raised -bd 1\n\
$w.top configure -relief raised -bd 1\n\
}\n\
option add *Dialog.msg.wrapLength 3i widgetDefault\n\
label $w.msg -justify left -text $data(-message)\n\
catch {$w.msg configure -font \\\n\
-Adobe-Times-Medium-R-Normal--*-180-*-*-*-*-*-*\n\
}\n\
pack $w.msg -in $w.top -side right -expand 1 -fill both -padx 3m -pady 3m\n\
if {$data(-icon) != \"\"} {\n\
label $w.bitmap -bitmap $data(-icon)\n\
pack $w.bitmap -in $w.top -side left -padx 3m -pady 3m\n\
}\n\
set i 0\n\
foreach but $buttons {\n\
set name [lindex $but 0]\n\
set opts [lrange $but 1 end]\n\
if {![string compare $opts {}]} {\n\
set capName \\\n\
[string toupper \\\n\
[string index $name 0]][string range $name 1 end]\n\
set opts [list -text $capName]\n\
}\n\
eval button $w.$name $opts -command [list \"set tkPriv(button) $name\"]\n\
if {![string compare $name $data(-default)]} {\n\
$w.$name configure -default active\n\
}\n\
pack $w.$name -in $w.bot -side left -expand 1 \\\n\
-padx 3m -pady 2m\n\
set underIdx [$w.$name cget -under]\n\
if {$underIdx >= 0} {\n\
set key [string index [$w.$name cget -text] $underIdx]\n\
bind $w <Alt-[string tolower $key]>  \"$w.$name invoke\"\n\
bind $w <Alt-[string toupper $key]>  \"$w.$name invoke\"\n\
}\n\
incr i\n\
}\n\
if {[string compare $data(-default) \"\"]} {\n\
bind $w <Return> \"tkButtonInvoke $w.$data(-default)\"\n\
}\n\
wm withdraw $w\n\
update idletasks\n\
set x [expr {[winfo screenwidth $w]/2 - [winfo reqwidth $w]/2 \\\n\
- [winfo vrootx [winfo parent $w]]}]\n\
set y [expr {[winfo screenheight $w]/2 - [winfo reqheight $w]/2 \\\n\
- [winfo vrooty [winfo parent $w]]}]\n\
wm geom $w +$x+$y\n\
wm deiconify $w\n\
set oldFocus [focus]\n\
set oldGrab [grab current $w]\n\
if {$oldGrab != \"\"} {\n\
set grabStatus [grab status $oldGrab]\n\
}\n\
grab $w\n\
if {[string compare $data(-default) \"\"]} {\n\
focus $w.$data(-default)\n\
} else {\n\
focus $w\n\
}\n\
tkwait variable tkPriv(button)\n\
catch {focus $oldFocus}\n\
destroy $w\n\
if {$oldGrab != \"\"} {\n\
if {$grabStatus == \"global\"} {\n\
grab -global $oldGrab\n\
} else {\n\
grab $oldGrab\n\
}\n\
}\n\
return $tkPriv(button)\n\
}\n\
";
