/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_optMenu[] = "\
proc tk_optionMenu {w varName firstValue args} {\n\
upvar #0 $varName var\n\
if {![info exists var]} {\n\
set var $firstValue\n\
}\n\
menubutton $w -textvariable $varName -indicatoron 1 -menu $w.menu \\\n\
-relief raised -bd 2 -highlightthickness 2 -anchor c \\\n\
-direction flush\n\
menu $w.menu -tearoff 0\n\
$w.menu add radiobutton -label $firstValue -variable $varName\n\
foreach i $args {\n\
$w.menu add radiobutton -label $i -variable $varName\n\
}\n\
return $w.menu\n\
}\n\
";
