/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_button[] = "\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
bind Radiobutton <Enter> {\n\
tkButtonEnter %W\n\
}\n\
bind Radiobutton <1> {\n\
tkButtonDown %W\n\
}\n\
bind Radiobutton <ButtonRelease-1> {\n\
tkButtonUp %W\n\
}\n\
bind Checkbutton <Enter> {\n\
tkButtonEnter %W\n\
}\n\
bind Checkbutton <1> {\n\
tkButtonDown %W\n\
}\n\
bind Checkbutton <ButtonRelease-1> {\n\
tkButtonUp %W\n\
}\n\
}\n\
if {$tcl_platform(platform) == \"windows\"} {\n\
bind Checkbutton <equal> {\n\
tkCheckRadioInvoke %W select\n\
}\n\
bind Checkbutton <plus> {\n\
tkCheckRadioInvoke %W select\n\
}\n\
bind Checkbutton <minus> {\n\
tkCheckRadioInvoke %W deselect\n\
}\n\
bind Checkbutton <1> {\n\
tkCheckRadioDown %W\n\
}\n\
bind Checkbutton <ButtonRelease-1> {\n\
tkButtonUp %W\n\
}\n\
bind Checkbutton <Enter> {\n\
tkCheckRadioEnter %W\n\
}\n\
bind Radiobutton <1> {\n\
tkCheckRadioDown %W\n\
}\n\
bind Radiobutton <ButtonRelease-1> {\n\
tkButtonUp %W\n\
}\n\
bind Radiobutton <Enter> {\n\
tkCheckRadioEnter %W\n\
}\n\
}\n\
if {$tcl_platform(platform) == \"unix\"} {\n\
bind Checkbutton <Return> {\n\
if {!$tk_strictMotif} {\n\
tkCheckRadioInvoke %W\n\
}\n\
}\n\
bind Radiobutton <Return> {\n\
if {!$tk_strictMotif} {\n\
tkCheckRadioInvoke %W\n\
}\n\
}\n\
bind Checkbutton <1> {\n\
tkCheckRadioInvoke %W\n\
}\n\
bind Radiobutton <1> {\n\
tkCheckRadioInvoke %W\n\
}\n\
bind Checkbutton <Enter> {\n\
tkButtonEnter %W\n\
}\n\
bind Radiobutton <Enter> {\n\
tkButtonEnter %W\n\
}\n\
}\n\
bind Button <space> {\n\
tkButtonInvoke %W\n\
}\n\
bind Checkbutton <space> {\n\
tkCheckRadioInvoke %W\n\
}\n\
bind Radiobutton <space> {\n\
tkCheckRadioInvoke %W\n\
}\n\
bind Button <FocusIn> {}\n\
bind Button <Enter> {\n\
tkButtonEnter %W\n\
}\n\
bind Button <Leave> {\n\
tkButtonLeave %W\n\
}\n\
bind Button <1> {\n\
tkButtonDown %W\n\
}\n\
bind Button <ButtonRelease-1> {\n\
tkButtonUp %W\n\
}\n\
bind Checkbutton <FocusIn> {}\n\
bind Checkbutton <Leave> {\n\
tkButtonLeave %W\n\
}\n\
bind Radiobutton <FocusIn> {}\n\
bind Radiobutton <Leave> {\n\
tkButtonLeave %W\n\
}\n\
if {$tcl_platform(platform) == \"windows\"} {\n\
proc tkButtonEnter w {\n\
global tkPriv\n\
if {[$w cget -state] != \"disabled\"} {\n\
if {$tkPriv(buttonWindow) == $w} {\n\
$w configure -state active -relief sunken\n\
}\n\
}\n\
set tkPriv(window) $w\n\
}\n\
proc tkButtonLeave w {\n\
global tkPriv\n\
if {[$w cget -state] != \"disabled\"} {\n\
$w config -state normal\n\
}\n\
if {$w == $tkPriv(buttonWindow)} {\n\
$w configure -relief $tkPriv(relief)\n\
}\n\
set tkPriv(window) \"\"\n\
}\n\
proc tkCheckRadioEnter w {\n\
global tkPriv\n\
if {[$w cget -state] != \"disabled\"} {\n\
if {$tkPriv(buttonWindow) == $w} {\n\
$w configure -state active\n\
}\n\
}\n\
set tkPriv(window) $w\n\
}\n\
proc tkButtonDown w {\n\
global tkPriv\n\
set tkPriv(relief) [lindex [$w conf -relief] 4]\n\
if {[$w cget -state] != \"disabled\"} {\n\
set tkPriv(buttonWindow) $w\n\
$w config -relief sunken -state active\n\
}\n\
}\n\
proc tkCheckRadioDown w {\n\
global tkPriv\n\
set tkPriv(relief) [lindex [$w conf -relief] 4]\n\
if {[$w cget -state] != \"disabled\"} {\n\
set tkPriv(buttonWindow) $w\n\
$w config -state active\n\
}\n\
}\n\
proc tkButtonUp w {\n\
global tkPriv\n\
if {$w == $tkPriv(buttonWindow)} {\n\
set tkPriv(buttonWindow) \"\"\n\
if {($w == $tkPriv(window))\n\
&& ([$w cget -state] != \"disabled\")} {\n\
$w config -relief $tkPriv(relief) -state normal\n\
uplevel #0 [list $w invoke]\n\
}\n\
}\n\
}\n\
}\n\
if {$tcl_platform(platform) == \"unix\"} {\n\
proc tkButtonEnter {w} {\n\
global tkPriv\n\
if {[$w cget -state] != \"disabled\"} {\n\
$w config -state active\n\
if {$tkPriv(buttonWindow) == $w} {\n\
$w configure -state active -relief sunken\n\
}\n\
}\n\
set tkPriv(window) $w\n\
}\n\
proc tkButtonLeave w {\n\
global tkPriv\n\
if {[$w cget -state] != \"disabled\"} {\n\
$w config -state normal\n\
}\n\
if {$w == $tkPriv(buttonWindow)} {\n\
$w configure -relief $tkPriv(relief)\n\
}\n\
set tkPriv(window) \"\"\n\
}\n\
proc tkButtonDown w {\n\
global tkPriv\n\
set tkPriv(relief) [lindex [$w config -relief] 4]\n\
if {[$w cget -state] != \"disabled\"} {\n\
set tkPriv(buttonWindow) $w\n\
$w config -relief sunken\n\
}\n\
}\n\
proc tkButtonUp w {\n\
global tkPriv\n\
if {$w == $tkPriv(buttonWindow)} {\n\
set tkPriv(buttonWindow) \"\"\n\
$w config -relief $tkPriv(relief)\n\
if {($w == $tkPriv(window))\n\
&& ([$w cget -state] != \"disabled\")} {\n\
uplevel #0 [list $w invoke]\n\
}\n\
}\n\
}\n\
}\n\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
proc tkButtonEnter {w} {\n\
global tkPriv\n\
if {[$w cget -state] != \"disabled\"} {\n\
if {$tkPriv(buttonWindow) == $w} {\n\
$w configure -state active\n\
}\n\
}\n\
set tkPriv(window) $w\n\
}\n\
proc tkButtonLeave w {\n\
global tkPriv\n\
if {$w == $tkPriv(buttonWindow)} {\n\
$w configure -state normal\n\
}\n\
set tkPriv(window) \"\"\n\
}\n\
proc tkButtonDown w {\n\
global tkPriv\n\
if {[$w cget -state] != \"disabled\"} {\n\
set tkPriv(buttonWindow) $w\n\
$w config -state active\n\
}\n\
}\n\
proc tkButtonUp w {\n\
global tkPriv\n\
if {$w == $tkPriv(buttonWindow)} {\n\
$w config -state normal\n\
set tkPriv(buttonWindow) \"\"\n\
if {($w == $tkPriv(window))\n\
&& ([$w cget -state] != \"disabled\")} {\n\
uplevel #0 [list $w invoke]\n\
}\n\
}\n\
}\n\
}\n\
proc tkButtonInvoke w {\n\
if {[$w cget -state] != \"disabled\"} {\n\
set oldRelief [$w cget -relief]\n\
set oldState [$w cget -state]\n\
$w configure -state active -relief sunken\n\
update idletasks\n\
after 100\n\
$w configure -state $oldState -relief $oldRelief\n\
uplevel #0 [list $w invoke]\n\
}\n\
}\n\
proc tkCheckRadioInvoke {w {cmd invoke}} {\n\
if {[$w cget -state] != \"disabled\"} {\n\
uplevel #0 [list $w $cmd]\n\
}\n\
}\n\
";
