/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_tk[] = "\
package require -exact Tk 8.0\n\
package require -exact Tcl 8.0\n\
if {[info exists auto_path]} {\n\
if {[lsearch -exact $auto_path $tk_library] < 0} {\n\
lappend auto_path $tk_library\n\
}\n\
}\n\
set tk_strictMotif 0\n\
proc tkScreenChanged screen {\n\
set x [string last . $screen]\n\
if {$x > 0} {\n\
set disp [string range $screen 0 [expr {$x - 1}]]\n\
} else {\n\
set disp $screen\n\
}\n\
uplevel #0 upvar #0 tkPriv.$disp tkPriv\n\
global tkPriv\n\
global tcl_platform\n\
if {[info exists tkPriv]} {\n\
set tkPriv(screen) $screen\n\
return\n\
}\n\
set tkPriv(activeMenu) {}\n\
set tkPriv(activeItem) {}\n\
set tkPriv(afterId) {}\n\
set tkPriv(buttons) 0\n\
set tkPriv(buttonWindow) {}\n\
set tkPriv(dragging) 0\n\
set tkPriv(focus) {}\n\
set tkPriv(grab) {}\n\
set tkPriv(initPos) {}\n\
set tkPriv(inMenubutton) {}\n\
set tkPriv(listboxPrev) {}\n\
set tkPriv(menuBar) {}\n\
set tkPriv(mouseMoved) 0\n\
set tkPriv(oldGrab) {}\n\
set tkPriv(popup) {}\n\
set tkPriv(postedMb) {}\n\
set tkPriv(pressX) 0\n\
set tkPriv(pressY) 0\n\
set tkPriv(prevPos) 0\n\
set tkPriv(screen) $screen\n\
set tkPriv(selectMode) char\n\
if {[string compare $tcl_platform(platform) \"unix\"] == 0} {\n\
set tkPriv(tearoff) 1\n\
} else {\n\
set tkPriv(tearoff) 0\n\
}\n\
set tkPriv(window) {}\n\
}\n\
tkScreenChanged [winfo screen .]\n\
proc tkEventMotifBindings {n1 dummy dummy} {\n\
upvar $n1 name\n\
if {$name} {\n\
set op delete\n\
} else {\n\
set op add\n\
}\n\
event $op <<Cut>> <Control-Key-w>\n\
event $op <<Copy>> <Meta-Key-w> \n\
event $op <<Paste>> <Control-Key-y>\n\
}\n\
switch $tcl_platform(platform) {\n\
\"unix\" {\n\
event add <<Cut>> <Control-Key-x> <Key-F20> \n\
event add <<Copy>> <Control-Key-c> <Key-F16>\n\
event add <<Paste>> <Control-Key-v> <Key-F18>\n\
event add <<PasteSelection>> <ButtonRelease-2>\n\
trace variable tk_strictMotif w tkEventMotifBindings\n\
set tk_strictMotif $tk_strictMotif\n\
}\n\
\"windows\" {\n\
event add <<Cut>> <Control-Key-x> <Shift-Key-Delete>\n\
event add <<Copy>> <Control-Key-c> <Control-Key-Insert>\n\
event add <<Paste>> <Control-Key-v> <Shift-Key-Insert>\n\
event add <<PasteSelection>> <ButtonRelease-2>\n\
}\n\
\"macintosh\" {\n\
event add <<Cut>> <Control-Key-x> <Key-F2> \n\
event add <<Copy>> <Control-Key-c> <Key-F3>\n\
event add <<Paste>> <Control-Key-v> <Key-F4>\n\
event add <<PasteSelection>> <ButtonRelease-2>\n\
event add <<Clear>> <Clear>\n\
}\n\
}\n\
if {$tcl_platform(platform) != \"macintosh\"} {\n\
}\n\
bind all <Tab> {tkTabToWindow [tk_focusNext %W]}\n\
bind all <Shift-Tab> {tkTabToWindow [tk_focusPrev %W]}\n\
proc tkCancelRepeat {} {\n\
global tkPriv\n\
after cancel $tkPriv(afterId)\n\
set tkPriv(afterId) {}\n\
}\n\
proc tkTabToWindow {w} {\n\
if {\"[winfo class $w]\" == \"Entry\"} {\n\
$w select range 0 end\n\
$w icur end\n\
}\n\
focus $w\n\
}\n\
";
