/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_comdlg[] = "\
proc tclParseConfigSpec {w specs flags argList} {\n\
upvar #0 $w data\n\
foreach spec $specs {\n\
if {[llength $spec] < 4} {\n\
error \"\\\"spec\\\" should contain 5 or 4 elements\"\n\
}\n\
set cmdsw [lindex $spec 0]\n\
set cmd($cmdsw) \"\"\n\
set rname($cmdsw)   [lindex $spec 1]\n\
set rclass($cmdsw)  [lindex $spec 2]\n\
set def($cmdsw)     [lindex $spec 3]\n\
set verproc($cmdsw) [lindex $spec 4]\n\
}\n\
if {([llength $argList]%2) != 0} {\n\
foreach {cmdsw value} $argList {\n\
if {![info exists cmd($cmdsw)]} {\n\
error \"unknown option \\\"$cmdsw\\\", must be [tclListValidFlags cmd]\"\n\
}\n\
}\n\
error \"value for \\\"[lindex $argList end]\\\" missing\"\n\
}\n\
foreach cmdsw [array names cmd] {\n\
set data($cmdsw) $def($cmdsw)\n\
}\n\
foreach {cmdsw value} $argList {\n\
if {![info exists cmd($cmdsw)]} {\n\
error \"unknown option \\\"$cmdsw\\\", must be [tclListValidFlags cmd]\"\n\
}\n\
set data($cmdsw) $value\n\
}\n\
}\n\
proc tclListValidFlags {v} {\n\
upvar $v cmd\n\
set len [llength [array names cmd]]\n\
set i 1\n\
set separator \"\"\n\
set errormsg \"\"\n\
foreach cmdsw [lsort [array names cmd]] {\n\
append errormsg \"$separator$cmdsw\"\n\
incr i\n\
if {$i == $len} {\n\
set separator \" or \"\n\
} else {\n\
set separator \", \"\n\
}\n\
}\n\
return $errormsg\n\
}\n\
proc tclSortNoCase {str1 str2} {\n\
return [string compare [string toupper $str1] [string toupper $str2]]\n\
}\n\
proc tclVerifyInteger {string} {\n\
lindex {1 2 3} $string\n\
}\n\
proc tkFocusGroup_Create {t} {\n\
global tkPriv\n\
if {[string compare [winfo toplevel $t] $t]} {\n\
error \"$t is not a toplevel window\"\n\
}\n\
if {![info exists tkPriv(fg,$t)]} {\n\
set tkPriv(fg,$t) 1\n\
set tkPriv(focus,$t) \"\"\n\
bind $t <FocusIn>  \"tkFocusGroup_In  $t %W %d\"\n\
bind $t <FocusOut> \"tkFocusGroup_Out $t %W %d\"\n\
bind $t <Destroy>  \"tkFocusGroup_Destroy $t %W\"\n\
}\n\
}\n\
proc tkFocusGroup_BindIn {t w cmd} {\n\
global tkFocusIn tkPriv\n\
if {![info exists tkPriv(fg,$t)]} {\n\
error \"focus group \\\"$t\\\" doesn't exist\"\n\
}\n\
set tkFocusIn($t,$w) $cmd\n\
}\n\
proc tkFocusGroup_BindOut {t w cmd} {\n\
global tkFocusOut tkPriv\n\
if {![info exists tkPriv(fg,$t)]} {\n\
error \"focus group \\\"$t\\\" doesn't exist\"\n\
}\n\
set tkFocusOut($t,$w) $cmd\n\
}\n\
proc tkFocusGroup_Destroy {t w} {\n\
global tkPriv tkFocusIn tkFocusOut\n\
if {![string compare $t $w]} {\n\
unset tkPriv(fg,$t)\n\
unset tkPriv(focus,$t) \n\
foreach name [array names tkFocusIn $t,*] {\n\
unset tkFocusIn($name)\n\
}\n\
foreach name [array names tkFocusOut $t,*] {\n\
unset tkFocusOut($name)\n\
}\n\
} else {\n\
if {[info exists tkPriv(focus,$t)]} {\n\
if {![string compare $tkPriv(focus,$t) $w]} {\n\
set tkPriv(focus,$t) \"\"\n\
}\n\
}\n\
catch {\n\
unset tkFocusIn($t,$w)\n\
}\n\
catch {\n\
unset tkFocusOut($t,$w)\n\
}\n\
}\n\
}\n\
proc tkFocusGroup_In {t w detail} {\n\
global tkPriv tkFocusIn\n\
if {![info exists tkFocusIn($t,$w)]} {\n\
set tkFocusIn($t,$w) \"\"\n\
return\n\
}\n\
if {![info exists tkPriv(focus,$t)]} {\n\
return\n\
}\n\
if {![string compare $tkPriv(focus,$t) $w]} {\n\
return\n\
} else {\n\
set tkPriv(focus,$t) $w\n\
eval $tkFocusIn($t,$w)\n\
}\n\
}\n\
proc tkFocusGroup_Out {t w detail} {\n\
global tkPriv tkFocusOut\n\
if {[string compare $detail NotifyNonlinear] &&\n\
[string compare $detail NotifyNonlinearVirtual]} {\n\
return\n\
}\n\
if {![info exists tkPriv(focus,$t)]} {\n\
return\n\
}\n\
if {![info exists tkFocusOut($t,$w)]} {\n\
return\n\
} else {\n\
eval $tkFocusOut($t,$w)\n\
set tkPriv(focus,$t) \"\"\n\
}\n\
}\n\
proc tkFDGetFileTypes {string} {\n\
foreach t $string {\n\
if {[llength $t] < 2 || [llength $t] > 3} {\n\
error \"bad file type \\\"$t\\\", should be \\\"typeName {extension ?extensions ...?} ?{macType ?macTypes ...?}?\\\"\"\n\
}\n\
eval lappend [list fileTypes([lindex $t 0])] [lindex $t 1]\n\
}\n\
set types {}\n\
foreach t $string {\n\
set label [lindex $t 0]\n\
set exts {}\n\
if {[info exists hasDoneType($label)]} {\n\
continue\n\
}\n\
set name \"$label (\"\n\
set sep \"\"\n\
foreach ext $fileTypes($label) {\n\
if {![string compare $ext \"\"]} {\n\
continue\n\
}\n\
regsub {^[.]} $ext \"*.\" ext\n\
if {![info exists hasGotExt($label,$ext)]} {\n\
append name $sep$ext\n\
lappend exts $ext\n\
set hasGotExt($label,$ext) 1\n\
}\n\
set sep ,\n\
}\n\
append name \")\"\n\
lappend types [list $name $exts]\n\
set hasDoneType($label) 1\n\
}\n\
return $types\n\
}\n\
";
