/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_xmfbox[] = "\
proc tkMotifFDialog {args} {\n\
global tkPriv\n\
set w __tk_filedialog\n\
upvar #0 $w data\n\
if {![string compare [lindex [info level 0] 0] tk_getOpenFile]} {\n\
set type open\n\
} else {\n\
set type save\n\
}\n\
tkMotifFDialog_Config $w $type $args\n\
if {![string compare $data(-parent) .]} {\n\
set w .$w\n\
} else {\n\
set w $data(-parent).$w\n\
}\n\
if {![winfo exists $w]} {\n\
tkMotifFDialog_Create $w\n\
} elseif {[string compare [winfo class $w] TkMotifFDialog]} {\n\
destroy $w\n\
tkMotifFDialog_Create $w\n\
} else {\n\
set data(fEnt) $w.top.f1.ent\n\
set data(dList) $w.top.f2.a.l\n\
set data(fList) $w.top.f2.b.l\n\
set data(sEnt) $w.top.f3.ent\n\
set data(okBtn) $w.bot.ok\n\
set data(filterBtn) $w.bot.filter\n\
set data(cancelBtn) $w.bot.cancel\n\
}\n\
wm transient $w $data(-parent)\n\
tkMotifFDialog_Update $w\n\
wm withdraw $w\n\
update idletasks\n\
set x [expr {[winfo screenwidth $w]/2 - [winfo reqwidth $w]/2 \\\n\
- [winfo vrootx [winfo parent $w]]}]\n\
set y [expr {[winfo screenheight $w]/2 - [winfo reqheight $w]/2 \\\n\
- [winfo vrooty [winfo parent $w]]}]\n\
wm geom $w +$x+$y\n\
wm deiconify $w\n\
wm title $w $data(-title)\n\
set oldFocus [focus]\n\
set oldGrab [grab current $w]\n\
if {$oldGrab != \"\"} {\n\
set grabStatus [grab status $oldGrab]\n\
}\n\
grab $w\n\
focus $data(sEnt)\n\
$data(sEnt) select from 0\n\
$data(sEnt) select to   end\n\
tkwait variable tkPriv(selectFilePath)\n\
catch {focus $oldFocus}\n\
grab release $w\n\
wm withdraw $w\n\
if {$oldGrab != \"\"} {\n\
if {$grabStatus == \"global\"} {\n\
grab -global $oldGrab\n\
} else {\n\
grab $oldGrab\n\
}\n\
}\n\
return $tkPriv(selectFilePath)\n\
}\n\
proc tkMotifFDialog_Config {w type argList} {\n\
upvar #0 $w data\n\
set data(type) $type\n\
set specs {\n\
{-defaultextension \"\" \"\" \"\"}\n\
{-filetypes \"\" \"\" \"\"}\n\
{-initialdir \"\" \"\" \"\"}\n\
{-initialfile \"\" \"\" \"\"}\n\
{-parent \"\" \"\" \".\"}\n\
{-title \"\" \"\" \"\"}\n\
}\n\
if {![info exists data(selectPath)]} {\n\
set data(selectPath) [pwd]\n\
set data(selectFile) \"\"\n\
}\n\
tclParseConfigSpec $w $specs \"\" $argList\n\
if {![string compare $data(-title) \"\"]} {\n\
if {![string compare $type \"open\"]} {\n\
set data(-title) \"Open\"\n\
} else {\n\
set data(-title) \"Save As\"\n\
}\n\
}\n\
if {[string compare $data(-initialdir) \"\"]} {\n\
if {[file isdirectory $data(-initialdir)]} {\n\
set data(selectPath) [glob $data(-initialdir)]\n\
} else {\n\
set data(selectPath) [pwd]\n\
}\n\
set old [pwd]\n\
cd $data(selectPath)\n\
set data(selectPath) [pwd]\n\
cd $old\n\
}\n\
set data(selectFile) $data(-initialfile)\n\
set data(-filetypes) [tkFDGetFileTypes $data(-filetypes)]\n\
if {![info exists data(filter)]} {\n\
set data(filter) *\n\
}\n\
if {![winfo exists $data(-parent)]} {\n\
error \"bad window path name \\\"$data(-parent)\\\"\"\n\
}\n\
}\n\
proc tkMotifFDialog_Create {w} {\n\
set dataName [lindex [split $w .] end]\n\
upvar #0 $dataName data\n\
toplevel $w -class TkMotifFDialog\n\
set top [frame $w.top -relief raised -bd 1]\n\
set bot [frame $w.bot -relief raised -bd 1]\n\
pack $w.bot -side bottom -fill x\n\
pack $w.top -side top -expand yes -fill both\n\
set f1 [frame $top.f1]\n\
set f2 [frame $top.f2]\n\
set f3 [frame $top.f3]\n\
pack $f1 -side top    -fill x\n\
pack $f3 -side bottom -fill x\n\
pack $f2 -expand yes -fill both\n\
set f2a [frame $f2.a]\n\
set f2b [frame $f2.b]\n\
grid $f2a -row 0 -column 0 -rowspan 1 -columnspan 1 -padx 4 -pady 4 \\\n\
-sticky news\n\
grid $f2b -row 0 -column 1 -rowspan 1 -columnspan 1 -padx 4 -pady 4 \\\n\
-sticky news\n\
grid rowconfig $f2 0    -minsize 0   -weight 1\n\
grid columnconfig $f2 0 -minsize 0   -weight 1\n\
grid columnconfig $f2 1 -minsize 150 -weight 2\n\
label $f1.lab -text \"Filter:\" -under 3 -anchor w\n\
entry $f1.ent\n\
pack $f1.lab -side top -fill x -padx 6 -pady 4\n\
pack $f1.ent -side top -fill x -padx 4 -pady 0\n\
set data(fEnt) $f1.ent\n\
set data(dList) [tkMotifFDialog_MakeSList $w $f2a Directory: 0 DList]\n\
set data(fList) [tkMotifFDialog_MakeSList $w $f2b Files:     2 FList]\n\
label $f3.lab -text \"Selection:\" -under 0 -anchor w\n\
entry $f3.ent\n\
pack $f3.lab -side top -fill x -padx 6 -pady 0\n\
pack $f3.ent -side top -fill x -padx 4 -pady 4\n\
set data(sEnt) $f3.ent\n\
set data(okBtn) [button $bot.ok     -text OK     -width 6 -under 0 \\\n\
-command \"tkMotifFDialog_OkCmd $w\"]\n\
set data(filterBtn) [button $bot.filter -text Filter -width 6 -under 0 \\\n\
-command \"tkMotifFDialog_FilterCmd $w\"]\n\
set data(cancelBtn) [button $bot.cancel -text Cancel -width 6 -under 0 \\\n\
-command \"tkMotifFDialog_CancelCmd $w\"]\n\
pack $bot.ok $bot.filter $bot.cancel -padx 10 -pady 10 -expand yes \\\n\
-side left\n\
bind $w <Alt-t> \"focus $data(fEnt)\"\n\
bind $w <Alt-d> \"focus $data(dList)\"\n\
bind $w <Alt-l> \"focus $data(fList)\"\n\
bind $w <Alt-s> \"focus $data(sEnt)\"\n\
bind $w <Alt-o> \"tkButtonInvoke $bot.ok    \"\n\
bind $w <Alt-f> \"tkButtonInvoke $bot.filter\"\n\
bind $w <Alt-c> \"tkButtonInvoke $bot.cancel\"\n\
bind $data(fEnt) <Return> \"tkMotifFDialog_ActivateFEnt $w\"\n\
bind $data(sEnt) <Return> \"tkMotifFDialog_ActivateSEnt $w\"\n\
wm protocol $w WM_DELETE_WINDOW \"tkMotifFDialog_CancelCmd $w\"\n\
}\n\
proc tkMotifFDialog_MakeSList {w f label under cmd} {\n\
label $f.lab -text $label -under $under -anchor w\n\
listbox $f.l -width 12 -height 5 -selectmode browse -exportselection 0\\\n\
-xscrollcommand \"$f.h set\" \\\n\
-yscrollcommand \"$f.v set\" \n\
scrollbar $f.v -orient vertical   -takefocus 0 \\\n\
-command \"$f.l yview\"\n\
scrollbar $f.h -orient horizontal -takefocus 0 \\\n\
-command \"$f.l xview\"\n\
grid $f.lab -row 0 -column 0 -sticky news -rowspan 1 -columnspan 2 \\\n\
-padx 2 -pady 2\n\
grid $f.l -row 1 -column 0 -rowspan 1 -columnspan 1 -sticky news\n\
grid $f.v -row 1 -column 1 -rowspan 1 -columnspan 1 -sticky news\n\
grid $f.h -row 2 -column 0 -rowspan 1 -columnspan 1 -sticky news\n\
grid rowconfig    $f 0 -weight 0 -minsize 0\n\
grid rowconfig    $f 1 -weight 1 -minsize 0\n\
grid columnconfig $f 0 -weight 1 -minsize 0\n\
set list $f.l\n\
bind $list <Up>        \"tkMotifFDialog_Browse$cmd $w\"\n\
bind $list <Down>      \"tkMotifFDialog_Browse$cmd $w\"\n\
bind $list <space>     \"tkMotifFDialog_Browse$cmd $w\"\n\
bind $list <1>         \"tkMotifFDialog_Browse$cmd $w\"\n\
bind $list <B1-Motion> \"tkMotifFDialog_Browse$cmd $w\"\n\
bind $list <Double-1>  \"tkMotifFDialog_Activate$cmd $w\"\n\
bind $list <Return>    \"tkMotifFDialog_Browse$cmd $w; tkMotifFDialog_Activate$cmd $w\"\n\
bindtags $list \"Listbox $list [winfo toplevel $list] all\"\n\
tkListBoxKeyAccel_Set $list\n\
return $f.l\n\
}\n\
proc tkMotifFDialog_BrowseDList {w} {\n\
upvar #0 [winfo name $w] data\n\
focus $data(dList)\n\
if {![string compare [$data(dList) curselection] \"\"]} {\n\
return\n\
}\n\
set subdir [$data(dList) get [$data(dList) curselection]]\n\
if {![string compare $subdir \"\"]} {\n\
return\n\
}\n\
$data(fList) selection clear 0 end\n\
set list [tkMotifFDialog_InterpFilter $w]\n\
set data(filter) [lindex $list 1]\n\
case $subdir {\n\
. {\n\
set newSpec [file join $data(selectPath) $data(filter)]\n\
}\n\
.. {\n\
set newSpec [file join [file dirname $data(selectPath)] \\\n\
$data(filter)]\n\
}\n\
default {\n\
set newSpec [file join $data(selectPath) $subdir $data(filter)]\n\
}\n\
}\n\
$data(fEnt) delete 0 end\n\
$data(fEnt) insert 0 $newSpec\n\
}\n\
proc tkMotifFDialog_ActivateDList {w} {\n\
upvar #0 [winfo name $w] data\n\
if {![string compare [$data(dList) curselection] \"\"]} {\n\
return\n\
}\n\
set subdir [$data(dList) get [$data(dList) curselection]]\n\
if {![string compare $subdir \"\"]} {\n\
return\n\
}\n\
$data(fList) selection clear 0 end\n\
case $subdir {\n\
. {\n\
set newDir $data(selectPath)\n\
}\n\
.. {\n\
set newDir [file dirname $data(selectPath)]\n\
}\n\
default {\n\
set newDir [file join $data(selectPath) $subdir]\n\
}\n\
}\n\
set data(selectPath) $newDir\n\
tkMotifFDialog_Update $w\n\
if {[string compare $subdir ..]} {\n\
$data(dList) selection set 0\n\
$data(dList) activate 0\n\
} else {\n\
$data(dList) selection set 1\n\
$data(dList) activate 1\n\
}\n\
}\n\
proc tkMotifFDialog_BrowseFList {w} {\n\
upvar #0 [winfo name $w] data\n\
focus $data(fList)\n\
if {![string compare [$data(fList) curselection] \"\"]} {\n\
return\n\
}\n\
set data(selectFile) [$data(fList) get [$data(fList) curselection]]\n\
if {![string compare $data(selectFile) \"\"]} {\n\
return\n\
}\n\
$data(dList) selection clear 0 end\n\
$data(fEnt) delete 0 end\n\
$data(fEnt) insert 0 [file join $data(selectPath) $data(filter)]\n\
$data(fEnt) xview end\n\
$data(sEnt) delete 0 end\n\
$data(sEnt) insert 0 [file join $data(selectPath) $data(selectFile)]\n\
$data(sEnt) xview end\n\
}\n\
proc tkMotifFDialog_ActivateFList {w} {\n\
upvar #0 [winfo name $w] data\n\
if {![string compare [$data(fList) curselection] \"\"]} {\n\
return\n\
}\n\
set data(selectFile) [$data(fList) get [$data(fList) curselection]]\n\
if {![string compare $data(selectFile) \"\"]} {\n\
return\n\
} else {\n\
tkMotifFDialog_ActivateSEnt $w\n\
}\n\
}\n\
proc tkMotifFDialog_ActivateFEnt {w} {\n\
upvar #0 [winfo name $w] data\n\
set list [tkMotifFDialog_InterpFilter $w]\n\
set data(selectPath) [lindex $list 0]\n\
set data(filter)    [lindex $list 1]\n\
tkMotifFDialog_Update $w\n\
}\n\
proc tkMotifFDialog_InterpFilter {w} {\n\
upvar #0 [winfo name $w] data\n\
set text [string trim [$data(fEnt) get]]\n\
if {![string compare [string index $text 0] ~]} {\n\
set list [file split $text]\n\
set tilde [lindex $list 0]\n\
catch {\n\
set tilde [glob $tilde]\n\
}\n\
set text [eval file join [concat $tilde [lrange $list 1 end]]]\n\
}\n\
set resolved [file join [file dirname $text] [file tail $text]]\n\
if {[file isdirectory $resolved]} {\n\
set dir $resolved\n\
set fil $data(filter)\n\
} else {\n\
set dir [file dirname $resolved]\n\
set fil [file tail    $resolved]\n\
}\n\
return [list $dir $fil]\n\
}\n\
proc tkMotifFDialog_ActivateSEnt {w} {\n\
global tkPriv\n\
upvar #0 [winfo name $w] data\n\
set selectFilePath [string trim [$data(sEnt) get]]\n\
set selectFile     [file tail    $selectFilePath]\n\
set selectPath     [file dirname $selectFilePath]\n\
if {![string compare $selectFilePath \"\"]} {\n\
tkMotifFDialog_FilterCmd $w\n\
return\n\
}\n\
if {[file isdirectory $selectFilePath]} {\n\
set data(selectPath) [glob $selectFilePath]\n\
set data(selectFile) \"\"\n\
tkMotifFDialog_Update $w\n\
return\n\
}\n\
if {[string compare [file pathtype $selectFilePath] \"absolute\"]} {\n\
tk_messageBox -icon warning -type ok \\\n\
-message \"\\\"$selectFilePath\\\" must be an absolute pathname\"\n\
return\n\
}\n\
if {![file exists $selectPath]} {\n\
tk_messageBox -icon warning -type ok \\\n\
-message \"Directory \\\"$selectPath\\\" does not exist.\"\n\
return\n\
}\n\
if {![file exists $selectFilePath]} {\n\
if {![string compare $data(type) open]} {\n\
tk_messageBox -icon warning -type ok \\\n\
-message \"File \\\"$selectFilePath\\\" does not exist.\"\n\
return\n\
}\n\
} else {\n\
if {![string compare $data(type) save]} {\n\
set message [format %s%s \\\n\
\"File \\\"$selectFilePath\\\" already exists.\\n\\n\" \\\n\
\"Replace existing file?\"]\n\
set answer [tk_messageBox -icon warning -type yesno \\\n\
-message $message]\n\
if {![string compare $answer \"no\"]} {\n\
return\n\
}\n\
}\n\
}\n\
set tkPriv(selectFilePath) $selectFilePath\n\
set tkPriv(selectFile)     $selectFile\n\
set tkPriv(selectPath)     $selectPath\n\
}\n\
proc tkMotifFDialog_OkCmd {w} {\n\
upvar #0 [winfo name $w] data\n\
tkMotifFDialog_ActivateSEnt $w\n\
}\n\
proc tkMotifFDialog_FilterCmd {w} {\n\
upvar #0 [winfo name $w] data\n\
tkMotifFDialog_ActivateFEnt $w\n\
}\n\
proc tkMotifFDialog_CancelCmd {w} {\n\
global tkPriv\n\
set tkPriv(selectFilePath) \"\"\n\
set tkPriv(selectFile)     \"\"\n\
set tkPriv(selectPath)     \"\"\n\
}\n\
proc tkMotifFDialog_Update {w} {\n\
upvar #0 [winfo name $w] data\n\
$data(fEnt) delete 0 end\n\
$data(fEnt) insert 0 [file join $data(selectPath) $data(filter)]\n\
$data(sEnt) delete 0 end\n\
$data(sEnt) insert 0 [file join $data(selectPath) $data(selectFile)]\n\
tkMotifFDialog_LoadFiles $w\n\
}\n\
proc tkMotifFDialog_LoadFiles {w} {\n\
upvar #0 [winfo name $w] data\n\
$data(dList) delete 0 end\n\
$data(fList) delete 0 end\n\
set appPWD [pwd]\n\
if {[catch {\n\
cd $data(selectPath)\n\
}]} {\n\
cd $appPWD\n\
$data(dList) insert end \"..\"\n\
return\n\
}\n\
foreach f [lsort -command tclSortNoCase [glob -nocomplain .* *]] {\n\
if {[file isdirectory $f]} {\n\
$data(dList) insert end $f\n\
}\n\
}\n\
if {![string compare $data(filter) *]} {\n\
set files [lsort -command tclSortNoCase [glob -nocomplain .* *]]\n\
} else {\n\
set files [lsort -command tclSortNoCase \\\n\
[glob -nocomplain $data(filter)]]\n\
}\n\
set top 0\n\
foreach f $files {\n\
if {![file isdir $f]} {\n\
$data(fList) insert end $f\n\
if {[string match .* $f]} {\n\
incr top\n\
}\n\
}\n\
}\n\
$data(fList) yview $top\n\
cd $appPWD\n\
}\n\
proc tkListBoxKeyAccel_Set {w} {\n\
bind Listbox <Any-KeyPress> \"\"\n\
bind $w <Destroy> \"tkListBoxKeyAccel_Unset $w\"\n\
bind $w <Any-KeyPress> \"tkListBoxKeyAccel_Key $w %A\"\n\
}\n\
proc tkListBoxKeyAccel_Unset {w} {\n\
global tkPriv\n\
catch {after cancel $tkPriv(lbAccel,$w,afterId)}\n\
catch {unset tkPriv(lbAccel,$w)}\n\
catch {unset tkPriv(lbAccel,$w,afterId)}\n\
}\n\
proc tkListBoxKeyAccel_Key {w key} {\n\
global tkPriv\n\
append tkPriv(lbAccel,$w) $key\n\
tkListBoxKeyAccel_Goto $w $tkPriv(lbAccel,$w)\n\
catch {\n\
after cancel $tkPriv(lbAccel,$w,afterId)\n\
}\n\
set tkPriv(lbAccel,$w,afterId) [after 500 tkListBoxKeyAccel_Reset $w]\n\
}\n\
proc tkListBoxKeyAccel_Goto {w string} {\n\
global tkPriv\n\
set string [string tolower $string]\n\
set end [$w index end]\n\
set theIndex -1\n\
for {set i 0} {$i < $end} {incr i} {\n\
set item [string tolower [$w get $i]]\n\
if {[string compare $string $item] >= 0} {\n\
set theIndex $i\n\
}\n\
if {[string compare $string $item] <= 0} {\n\
set theIndex $i\n\
break\n\
}\n\
}\n\
if {$theIndex >= 0} {\n\
$w selection clear 0 end\n\
$w selection set $theIndex $theIndex\n\
$w activate $theIndex\n\
$w see $theIndex\n\
}\n\
}\n\
proc tkListBoxKeyAccel_Reset {w} {\n\
global tkPriv\n\
catch {unset tkPriv(lbAccel,$w)}\n\
}\n\
";
