/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_safetk[] = "\
package require opt 0.1;\n\
namespace eval ::safe {\n\
variable tkSafeId 0;\n\
proc ::safe::tkInterpInit {slave argv} {\n\
global env tk_library\n\
allowTk $slave $argv\n\
::interp eval $slave [list set tk_library [::safe::interpAddToAccessPath $slave $tk_library]]\n\
return $slave;\n\
}\n\
proc ::safe::loadTk {} {}\n\
::tcl::OptProc loadTk {\n\
{slave -interp \"name of the slave interpreter\"}\n\
{-use  -windowId {} \"window Id to use (new toplevel otherwise)\"}\n\
{-display -displayName {} \"display name to use (current one otherwise)\"}\n\
} {\n\
set displayGiven [::tcl::OptProcArgGiven \"-display\"]\n\
if {!$displayGiven} {\n\
if {[catch {set display [winfo screen .]}]} {\n\
if {[info exists ::env(DISPLAY)]} {\n\
set display $::env(DISPLAY)\n\
} else {\n\
Log $slave \"no winfo screen . nor env(DISPLAY)\" WARNING\n\
set display \":0.0\"\n\
}\n\
}\n\
}\n\
if {![::tcl::OptProcArgGiven \"-use\"]} {\n\
::tcl::Lassign [tkTopLevel $slave $display] w use;\n\
Set [DeleteHookName $slave] [list tkDelete {} $w];\n\
} else {\n\
if {[string match \".*\" $use]} {\n\
set windowName $use\n\
set use [winfo id $windowName]\n\
set nDisplay [winfo screen $windowName]\n\
} else {\n\
if {![catch {winfo pathname $use} name]} {\n\
set nDisplay [winfo screen $name]\n\
} else {\n\
set nDisplay $display\n\
}\n\
}\n\
if {[string compare $nDisplay $display]} {\n\
if {$displayGiven} {\n\
error \"conflicting -display $display and -use\\\n\
$use -> $nDisplay\"\n\
} else {\n\
set display $nDisplay\n\
}\n\
}\n\
}\n\
tkInterpInit $slave [list \"-use\" $use \"-display\" $display]\n\
load {} Tk $slave\n\
return $slave\n\
}\n\
proc ::safe::TkInit {interpPath} {\n\
variable tkInit\n\
if {[info exists tkInit($interpPath)]} {\n\
set value $tkInit($interpPath)\n\
Log $interpPath \"TkInit called, returning \\\"$value\\\"\" NOTICE\n\
return $value\n\
} else {\n\
Log $interpPath \"TkInit called for interp with clearance:\\\n\
preventing Tk init\" ERROR\n\
error \"not allowed\"\n\
}\n\
}\n\
proc ::safe::allowTk {interpPath argv} {\n\
variable tkInit\n\
set tkInit($interpPath) $argv\n\
}\n\
proc ::safe::tkDelete {W window slave} {\n\
Log $slave \"Called tkDelete $W $window\" NOTICE;\n\
if {[::interp exists $slave]} {\n\
if {[catch {::safe::interpDelete $slave} msg]} {\n\
Log $slave \"Deletion error : $msg\";\n\
}\n\
}\n\
if {[winfo exists $window]} {\n\
Log $slave \"Destroy toplevel $window\" NOTICE;\n\
destroy $window;\n\
}\n\
}\n\
proc ::safe::tkTopLevel {slave display} {\n\
variable tkSafeId;\n\
incr tkSafeId;\n\
set w \".safe$tkSafeId\";\n\
if {[catch {toplevel $w -screen $display -class SafeTk} msg]} {\n\
return -code error \"Unable to create toplevel for\\\n\
safe slave \\\"$slave\\\" ($msg)\";\n\
}\n\
Log $slave \"New toplevel $w\" NOTICE\n\
set msg \"Untrusted Tcl applet ($slave)\"\n\
wm title $w $msg;\n\
set wc $w.fc\n\
frame $wc -bg red -borderwidth 3 -relief ridge ;\n\
bindtags $wc [concat Safe$wc [bindtags $wc]]\n\
bind Safe$wc <Destroy> [list ::safe::tkDelete %W $w $slave];\n\
label $wc.l -text $msg \\\n\
-padx 2 -pady 0 -anchor w;\n\
frame  $wc.fb -bd 0 ;\n\
button $wc.fb.b -text \"Delete\" \\\n\
-bd 1  -padx 2 -pady 0 -highlightthickness 0 \\\n\
-command [list ::safe::tkDelete $w $w $slave]\n\
pack $wc.fb.b -side right -fill both ;\n\
pack $wc.fb -side right -fill both -expand 1;\n\
pack $wc.l -side left  -fill both -expand 1;\n\
pack $wc -side bottom -fill x ;\n\
frame $w.c -container 1;\n\
pack $w.c -fill both -expand 1;\n\
list $w [winfo id $w.c] ;\n\
}\n\
}\n\
";
