/* This file is automatically generated by tcl2c, do NOT edit by hand! */
char lib_text[] = "\
bind Text <1> {\n\
tkTextButton1 %W %x %y\n\
%W tag remove sel 0.0 end\n\
}\n\
bind Text <B1-Motion> {\n\
set tkPriv(x) %x\n\
set tkPriv(y) %y\n\
tkTextSelectTo %W %x %y\n\
}\n\
bind Text <Double-1> {\n\
set tkPriv(selectMode) word\n\
tkTextSelectTo %W %x %y\n\
catch {%W mark set insert sel.first}\n\
}\n\
bind Text <Triple-1> {\n\
set tkPriv(selectMode) line\n\
tkTextSelectTo %W %x %y\n\
catch {%W mark set insert sel.first}\n\
}\n\
bind Text <Shift-1> {\n\
tkTextResetAnchor %W @%x,%y\n\
set tkPriv(selectMode) char\n\
tkTextSelectTo %W %x %y\n\
}\n\
bind Text <Double-Shift-1>	{\n\
set tkPriv(selectMode) word\n\
tkTextSelectTo %W %x %y\n\
}\n\
bind Text <Triple-Shift-1>	{\n\
set tkPriv(selectMode) line\n\
tkTextSelectTo %W %x %y\n\
}\n\
bind Text <B1-Leave> {\n\
set tkPriv(x) %x\n\
set tkPriv(y) %y\n\
tkTextAutoScan %W\n\
}\n\
bind Text <B1-Enter> {\n\
tkCancelRepeat\n\
}\n\
bind Text <ButtonRelease-1> {\n\
tkCancelRepeat\n\
}\n\
bind Text <Control-1> {\n\
%W mark set insert @%x,%y\n\
}\n\
bind Text <Left> {\n\
tkTextSetCursor %W insert-1c\n\
}\n\
bind Text <Right> {\n\
tkTextSetCursor %W insert+1c\n\
}\n\
bind Text <Up> {\n\
tkTextSetCursor %W [tkTextUpDownLine %W -1]\n\
}\n\
bind Text <Down> {\n\
tkTextSetCursor %W [tkTextUpDownLine %W 1]\n\
}\n\
bind Text <Shift-Left> {\n\
tkTextKeySelect %W [%W index {insert - 1c}]\n\
}\n\
bind Text <Shift-Right> {\n\
tkTextKeySelect %W [%W index {insert + 1c}]\n\
}\n\
bind Text <Shift-Up> {\n\
tkTextKeySelect %W [tkTextUpDownLine %W -1]\n\
}\n\
bind Text <Shift-Down> {\n\
tkTextKeySelect %W [tkTextUpDownLine %W 1]\n\
}\n\
bind Text <Control-Left> {\n\
tkTextSetCursor %W [tkTextPrevPos %W insert tcl_startOfPreviousWord]\n\
}\n\
bind Text <Control-Right> {\n\
tkTextSetCursor %W [tkTextNextWord %W insert]\n\
}\n\
bind Text <Control-Up> {\n\
tkTextSetCursor %W [tkTextPrevPara %W insert]\n\
}\n\
bind Text <Control-Down> {\n\
tkTextSetCursor %W [tkTextNextPara %W insert]\n\
}\n\
bind Text <Shift-Control-Left> {\n\
tkTextKeySelect %W [tkTextPrevPos %W insert tcl_startOfPreviousWord]\n\
}\n\
bind Text <Shift-Control-Right> {\n\
tkTextKeySelect %W [tkTextNextWord %W insert]\n\
}\n\
bind Text <Shift-Control-Up> {\n\
tkTextKeySelect %W [tkTextPrevPara %W insert]\n\
}\n\
bind Text <Shift-Control-Down> {\n\
tkTextKeySelect %W [tkTextNextPara %W insert]\n\
}\n\
bind Text <Prior> {\n\
tkTextSetCursor %W [tkTextScrollPages %W -1]\n\
}\n\
bind Text <Shift-Prior> {\n\
tkTextKeySelect %W [tkTextScrollPages %W -1]\n\
}\n\
bind Text <Next> {\n\
tkTextSetCursor %W [tkTextScrollPages %W 1]\n\
}\n\
bind Text <Shift-Next> {\n\
tkTextKeySelect %W [tkTextScrollPages %W 1]\n\
}\n\
bind Text <Control-Prior> {\n\
%W xview scroll -1 page\n\
}\n\
bind Text <Control-Next> {\n\
%W xview scroll 1 page\n\
}\n\
bind Text <Home> {\n\
tkTextSetCursor %W {insert linestart}\n\
}\n\
bind Text <Shift-Home> {\n\
tkTextKeySelect %W {insert linestart}\n\
}\n\
bind Text <End> {\n\
tkTextSetCursor %W {insert lineend}\n\
}\n\
bind Text <Shift-End> {\n\
tkTextKeySelect %W {insert lineend}\n\
}\n\
bind Text <Control-Home> {\n\
tkTextSetCursor %W 1.0\n\
}\n\
bind Text <Control-Shift-Home> {\n\
tkTextKeySelect %W 1.0\n\
}\n\
bind Text <Control-End> {\n\
tkTextSetCursor %W {end - 1 char}\n\
}\n\
bind Text <Control-Shift-End> {\n\
tkTextKeySelect %W {end - 1 char}\n\
}\n\
bind Text <Tab> {\n\
tkTextInsert %W \\t\n\
focus %W\n\
break\n\
}\n\
bind Text <Shift-Tab> {\n\
break\n\
}\n\
bind Text <Control-Tab> {\n\
focus [tk_focusNext %W]\n\
}\n\
bind Text <Control-Shift-Tab> {\n\
focus [tk_focusPrev %W]\n\
}\n\
bind Text <Control-i> {\n\
tkTextInsert %W \\t\n\
}\n\
bind Text <Return> {\n\
tkTextInsert %W \\n\n\
}\n\
bind Text <Delete> {\n\
if {[%W tag nextrange sel 1.0 end] != \"\"} {\n\
%W delete sel.first sel.last\n\
} else {\n\
%W delete insert\n\
%W see insert\n\
}\n\
}\n\
bind Text <BackSpace> {\n\
if {[%W tag nextrange sel 1.0 end] != \"\"} {\n\
%W delete sel.first sel.last\n\
} elseif {[%W compare insert != 1.0]} {\n\
%W delete insert-1c\n\
%W see insert\n\
}\n\
}\n\
bind Text <Control-space> {\n\
%W mark set anchor insert\n\
}\n\
bind Text <Select> {\n\
%W mark set anchor insert\n\
}\n\
bind Text <Control-Shift-space> {\n\
set tkPriv(selectMode) char\n\
tkTextKeyExtend %W insert\n\
}\n\
bind Text <Shift-Select> {\n\
set tkPriv(selectMode) char\n\
tkTextKeyExtend %W insert\n\
}\n\
bind Text <Control-slash> {\n\
%W tag add sel 1.0 end\n\
}\n\
bind Text <Control-backslash> {\n\
%W tag remove sel 1.0 end\n\
}\n\
bind Text <<Cut>> {\n\
tk_textCut %W\n\
}\n\
bind Text <<Copy>> {\n\
tk_textCopy %W\n\
}\n\
bind Text <<Paste>> {\n\
tk_textPaste %W\n\
}\n\
bind Text <<Clear>> {\n\
catch {%W delete sel.first sel.last}\n\
}\n\
bind Text <<PasteSelection>> {\n\
if {!$tkPriv(mouseMoved) || $tk_strictMotif} {\n\
tkTextPaste %W %x %y\n\
}\n\
}\n\
bind Text <Insert> {\n\
catch {tkTextInsert %W [selection get -displayof %W]}\n\
}\n\
bind Text <KeyPress> {\n\
tkTextInsert %W %A\n\
}\n\
bind Text <Alt-KeyPress> {# nothing }\n\
bind Text <Meta-KeyPress> {# nothing}\n\
bind Text <Control-KeyPress> {# nothing}\n\
bind Text <Escape> {# nothing}\n\
bind Text <KP_Enter> {# nothing}\n\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
bind Text <Command-KeyPress> {# nothing}\n\
}\n\
bind Text <Control-a> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W {insert linestart}\n\
}\n\
}\n\
bind Text <Control-b> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W insert-1c\n\
}\n\
}\n\
bind Text <Control-d> {\n\
if {!$tk_strictMotif} {\n\
%W delete insert\n\
}\n\
}\n\
bind Text <Control-e> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W {insert lineend}\n\
}\n\
}\n\
bind Text <Control-f> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W insert+1c\n\
}\n\
}\n\
bind Text <Control-k> {\n\
if {!$tk_strictMotif} {\n\
if {[%W compare insert == {insert lineend}]} {\n\
%W delete insert\n\
} else {\n\
%W delete insert {insert lineend}\n\
}\n\
}\n\
}\n\
bind Text <Control-n> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W [tkTextUpDownLine %W 1]\n\
}\n\
}\n\
bind Text <Control-o> {\n\
if {!$tk_strictMotif} {\n\
%W insert insert \\n\n\
%W mark set insert insert-1c\n\
}\n\
}\n\
bind Text <Control-p> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W [tkTextUpDownLine %W -1]\n\
}\n\
}\n\
bind Text <Control-t> {\n\
if {!$tk_strictMotif} {\n\
tkTextTranspose %W\n\
}\n\
}\n\
if {$tcl_platform(platform) != \"windows\"} {\n\
bind Text <Control-v> {\n\
if {!$tk_strictMotif} {\n\
tkTextScrollPages %W 1\n\
}\n\
}\n\
}\n\
bind Text <Meta-b> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W [tkTextPrevPos %W insert tcl_startOfPreviousWord]\n\
}\n\
}\n\
bind Text <Meta-d> {\n\
if {!$tk_strictMotif} {\n\
%W delete insert [tkTextNextWord %W insert]\n\
}\n\
}\n\
bind Text <Meta-f> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W [tkTextNextWord %W insert]\n\
}\n\
}\n\
bind Text <Meta-less> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W 1.0\n\
}\n\
}\n\
bind Text <Meta-greater> {\n\
if {!$tk_strictMotif} {\n\
tkTextSetCursor %W end-1c\n\
}\n\
}\n\
bind Text <Meta-BackSpace> {\n\
if {!$tk_strictMotif} {\n\
%W delete [tkTextPrevPos %W insert tcl_startOfPreviousWord] insert\n\
}\n\
}\n\
bind Text <Meta-Delete> {\n\
if {!$tk_strictMotif} {\n\
%W delete [tkTextPrevPos %W insert tcl_startOfPreviousWord] insert\n\
}\n\
}\n\
if {$tcl_platform(platform) == \"macintosh\"} {\n\
bind Text <FocusIn> {\n\
%W tag configure sel -borderwidth 0\n\
%W configure -selectbackground systemHighlight -selectforeground systemHighlightText\n\
}\n\
bind Text <FocusOut> {\n\
%W tag configure sel -borderwidth 1\n\
%W configure -selectbackground white -selectforeground black\n\
}\n\
bind Text <Option-Left> {\n\
tkTextSetCursor %W [tkTextPrevPos %W insert tcl_startOfPreviousWord]\n\
}\n\
bind Text <Option-Right> {\n\
tkTextSetCursor %W [tkTextNextWord %W insert]\n\
}\n\
bind Text <Option-Up> {\n\
tkTextSetCursor %W [tkTextPrevPara %W insert]\n\
}\n\
bind Text <Option-Down> {\n\
tkTextSetCursor %W [tkTextNextPara %W insert]\n\
}\n\
bind Text <Shift-Option-Left> {\n\
tkTextKeySelect %W [tkTextPrevPos %W insert tcl_startOfPreviousWord]\n\
}\n\
bind Text <Shift-Option-Right> {\n\
tkTextKeySelect %W [tkTextNextWord %W insert]\n\
}\n\
bind Text <Shift-Option-Up> {\n\
tkTextKeySelect %W [tkTextPrevPara %W insert]\n\
}\n\
bind Text <Shift-Option-Down> {\n\
tkTextKeySelect %W [tkTextNextPara %W insert]\n\
}\n\
}\n\
bind Text <Control-h> {\n\
if {!$tk_strictMotif} {\n\
if {[%W compare insert != 1.0]} {\n\
%W delete insert-1c\n\
%W see insert\n\
}\n\
}\n\
}\n\
bind Text <2> {\n\
if {!$tk_strictMotif} {\n\
%W scan mark %x %y\n\
set tkPriv(x) %x\n\
set tkPriv(y) %y\n\
set tkPriv(mouseMoved) 0\n\
}\n\
}\n\
bind Text <B2-Motion> {\n\
if {!$tk_strictMotif} {\n\
if {(%x != $tkPriv(x)) || (%y != $tkPriv(y))} {\n\
set tkPriv(mouseMoved) 1\n\
}\n\
if {$tkPriv(mouseMoved)} {\n\
%W scan dragto %x %y\n\
}\n\
}\n\
}\n\
set tkPriv(prevPos) {}\n\
proc tkTextClosestGap {w x y} {\n\
set pos [$w index @$x,$y]\n\
set bbox [$w bbox $pos]\n\
if {![string compare $bbox \"\"]} {\n\
return $pos\n\
}\n\
if {($x - [lindex $bbox 0]) < ([lindex $bbox 2]/2)} {\n\
return $pos\n\
}\n\
$w index \"$pos + 1 char\"\n\
}\n\
proc tkTextButton1 {w x y} {\n\
global tkPriv\n\
set tkPriv(selectMode) char\n\
set tkPriv(mouseMoved) 0\n\
set tkPriv(pressX) $x\n\
$w mark set insert [tkTextClosestGap $w $x $y]\n\
$w mark set anchor insert\n\
if {[$w cget -state] == \"normal\"} {focus $w}\n\
}\n\
proc tkTextSelectTo {w x y} {\n\
global tkPriv tcl_platform\n\
set cur [tkTextClosestGap $w $x $y]\n\
if {[catch {$w index anchor}]} {\n\
$w mark set anchor $cur\n\
}\n\
set anchor [$w index anchor]\n\
if {[$w compare $cur != $anchor] || (abs($tkPriv(pressX) - $x) >= 3)} {\n\
set tkPriv(mouseMoved) 1\n\
}\n\
switch $tkPriv(selectMode) {\n\
char {\n\
if {[$w compare $cur < anchor]} {\n\
set first $cur\n\
set last anchor\n\
} else {\n\
set first anchor\n\
set last $cur\n\
}\n\
}\n\
word {\n\
if {[$w compare $cur < anchor]} {\n\
set first [tkTextPrevPos $w \"$cur + 1c\" tcl_wordBreakBefore]\n\
set last [tkTextNextPos $w \"anchor\" tcl_wordBreakAfter]\n\
} else {\n\
set first [tkTextPrevPos $w anchor tcl_wordBreakBefore]\n\
set last [tkTextNextPos $w \"$cur - 1c\" tcl_wordBreakAfter]\n\
}\n\
}\n\
line {\n\
if {[$w compare $cur < anchor]} {\n\
set first [$w index \"$cur linestart\"]\n\
set last [$w index \"anchor - 1c lineend + 1c\"]\n\
} else {\n\
set first [$w index \"anchor linestart\"]\n\
set last [$w index \"$cur lineend + 1c\"]\n\
}\n\
}\n\
}\n\
if {$tkPriv(mouseMoved) || ($tkPriv(selectMode) != \"char\")} {\n\
if {$tcl_platform(platform) != \"unix\" && [$w compare $cur < anchor]} {\n\
$w mark set insert $first\n\
} else {\n\
$w mark set insert $last\n\
}\n\
$w tag remove sel 0.0 $first\n\
$w tag add sel $first $last\n\
$w tag remove sel $last end\n\
update idletasks\n\
}\n\
}\n\
proc tkTextKeyExtend {w index} {\n\
global tkPriv\n\
set cur [$w index $index]\n\
if {[catch {$w index anchor}]} {\n\
$w mark set anchor $cur\n\
}\n\
set anchor [$w index anchor]\n\
if {[$w compare $cur < anchor]} {\n\
set first $cur\n\
set last anchor\n\
} else {\n\
set first anchor\n\
set last $cur\n\
}\n\
$w tag remove sel 0.0 $first\n\
$w tag add sel $first $last\n\
$w tag remove sel $last end\n\
}\n\
proc tkTextPaste {w x y} {\n\
$w mark set insert [tkTextClosestGap $w $x $y]\n\
catch {$w insert insert [selection get -displayof $w]}\n\
if {[$w cget -state] == \"normal\"} {focus $w}\n\
}\n\
proc tkTextAutoScan {w} {\n\
global tkPriv\n\
if {![winfo exists $w]} return\n\
if {$tkPriv(y) >= [winfo height $w]} {\n\
$w yview scroll 2 units\n\
} elseif {$tkPriv(y) < 0} {\n\
$w yview scroll -2 units\n\
} elseif {$tkPriv(x) >= [winfo width $w]} {\n\
$w xview scroll 2 units\n\
} elseif {$tkPriv(x) < 0} {\n\
$w xview scroll -2 units\n\
} else {\n\
return\n\
}\n\
tkTextSelectTo $w $tkPriv(x) $tkPriv(y)\n\
set tkPriv(afterId) [after 50 tkTextAutoScan $w]\n\
}\n\
proc tkTextSetCursor {w pos} {\n\
global tkPriv\n\
if {[$w compare $pos == end]} {\n\
set pos {end - 1 chars}\n\
}\n\
$w mark set insert $pos\n\
$w tag remove sel 1.0 end\n\
$w see insert\n\
}\n\
proc tkTextKeySelect {w new} {\n\
global tkPriv\n\
if {[$w tag nextrange sel 1.0 end] == \"\"} {\n\
if {[$w compare $new < insert]} {\n\
$w tag add sel $new insert\n\
} else {\n\
$w tag add sel insert $new\n\
}\n\
$w mark set anchor insert\n\
} else {\n\
if {[$w compare $new < anchor]} {\n\
set first $new\n\
set last anchor\n\
} else {\n\
set first anchor\n\
set last $new\n\
}\n\
$w tag remove sel 1.0 $first\n\
$w tag add sel $first $last\n\
$w tag remove sel $last end\n\
}\n\
$w mark set insert $new\n\
$w see insert\n\
update idletasks\n\
}\n\
proc tkTextResetAnchor {w index} {\n\
global tkPriv\n\
if {[$w tag ranges sel] == \"\"} {\n\
$w mark set anchor $index\n\
return\n\
}\n\
set a [$w index $index]\n\
set b [$w index sel.first]\n\
set c [$w index sel.last]\n\
if {[$w compare $a < $b]} {\n\
$w mark set anchor sel.last\n\
return\n\
}\n\
if {[$w compare $a > $c]} {\n\
$w mark set anchor sel.first\n\
return\n\
}\n\
scan $a \"%d.%d\" lineA chA\n\
scan $b \"%d.%d\" lineB chB\n\
scan $c \"%d.%d\" lineC chC\n\
if {$lineB < $lineC+2} {\n\
set total [string length [$w get $b $c]]\n\
if {$total <= 2} {\n\
return\n\
}\n\
if {[string length [$w get $b $a]] < ($total/2)} {\n\
$w mark set anchor sel.last\n\
} else {\n\
$w mark set anchor sel.first\n\
}\n\
return\n\
}\n\
if {($lineA-$lineB) < ($lineC-$lineA)} {\n\
$w mark set anchor sel.last\n\
} else {\n\
$w mark set anchor sel.first\n\
}\n\
}\n\
proc tkTextInsert {w s} {\n\
if {($s == \"\") || ([$w cget -state] == \"disabled\")} {\n\
return\n\
}\n\
catch {\n\
if {[$w compare sel.first <= insert]\n\
&& [$w compare sel.last >= insert]} {\n\
$w delete sel.first sel.last\n\
}\n\
}\n\
$w insert insert $s\n\
$w see insert\n\
}\n\
proc tkTextUpDownLine {w n} {\n\
global tkPriv\n\
set i [$w index insert]\n\
scan $i \"%d.%d\" line char\n\
if {[string compare $tkPriv(prevPos) $i] != 0} {\n\
set tkPriv(char) $char\n\
}\n\
set new [$w index [expr {$line + $n}].$tkPriv(char)]\n\
if {[$w compare $new == end] || [$w compare $new == \"insert linestart\"]} {\n\
set new $i\n\
}\n\
set tkPriv(prevPos) $new\n\
return $new\n\
}\n\
proc tkTextPrevPara {w pos} {\n\
set pos [$w index \"$pos linestart\"]\n\
while 1 {\n\
if {(([$w get \"$pos - 1 line\"] == \"\\n\") && ([$w get $pos] != \"\\n\"))\n\
|| ($pos == \"1.0\")} {\n\
if {[regexp -indices {^[ 	]+(.)} [$w get $pos \"$pos lineend\"] \\\n\
dummy index]} {\n\
set pos [$w index \"$pos + [lindex $index 0] chars\"]\n\
}\n\
if {[$w compare $pos != insert] || ($pos == \"1.0\")} {\n\
return $pos\n\
}\n\
}\n\
set pos [$w index \"$pos - 1 line\"]\n\
}\n\
}\n\
proc tkTextNextPara {w start} {\n\
set pos [$w index \"$start linestart + 1 line\"]\n\
while {[$w get $pos] != \"\\n\"} {\n\
if {[$w compare $pos == end]} {\n\
return [$w index \"end - 1c\"]\n\
}\n\
set pos [$w index \"$pos + 1 line\"]\n\
}\n\
while {[$w get $pos] == \"\\n\"} {\n\
set pos [$w index \"$pos + 1 line\"]\n\
if {[$w compare $pos == end]} {\n\
return [$w index \"end - 1c\"]\n\
}\n\
}\n\
if {[regexp -indices {^[ 	]+(.)} [$w get $pos \"$pos lineend\"] \\\n\
dummy index]} {\n\
return [$w index \"$pos + [lindex $index 0] chars\"]\n\
}\n\
return $pos\n\
}\n\
proc tkTextScrollPages {w count} {\n\
set bbox [$w bbox insert]\n\
$w yview scroll $count pages\n\
if {$bbox == \"\"} {\n\
return [$w index @[expr {[winfo height $w]/2}],0]\n\
}\n\
return [$w index @[lindex $bbox 0],[lindex $bbox 1]]\n\
}\n\
proc tkTextTranspose w {\n\
set pos insert\n\
if {[$w compare $pos != \"$pos lineend\"]} {\n\
set pos [$w index \"$pos + 1 char\"]\n\
}\n\
set new [$w get \"$pos - 1 char\"][$w get  \"$pos - 2 char\"]\n\
if {[$w compare \"$pos - 1 char\" == 1.0]} {\n\
return\n\
}\n\
$w delete \"$pos - 2 char\" $pos\n\
$w insert insert $new\n\
$w see insert\n\
}\n\
proc tk_textCopy w {\n\
if {![catch {set data [$w get sel.first sel.last]}]} {\n\
clipboard clear -displayof $w\n\
clipboard append -displayof $w $data\n\
}\n\
}\n\
proc tk_textCut w {\n\
if {![catch {set data [$w get sel.first sel.last]}]} {\n\
clipboard clear -displayof $w\n\
clipboard append -displayof $w $data\n\
$w delete sel.first sel.last\n\
}\n\
}\n\
proc tk_textPaste w {\n\
global tcl_platform\n\
catch {\n\
if {\"$tcl_platform(platform)\" != \"unix\"} {\n\
catch {\n\
$w delete sel.first sel.last\n\
}\n\
}\n\
$w insert insert [selection get -displayof $w -selection CLIPBOARD]\n\
}\n\
}\n\
if {$tcl_platform(platform) == \"windows\"}  {\n\
proc tkTextNextWord {w start} {\n\
tkTextNextPos $w [tkTextNextPos $w $start tcl_endOfWord] \\\n\
tcl_startOfNextWord\n\
}\n\
} else {\n\
proc tkTextNextWord {w start} {\n\
tkTextNextPos $w $start tcl_endOfWord\n\
}\n\
}\n\
proc tkTextNextPos {w start op} {\n\
set text \"\"\n\
set cur $start\n\
while {[$w compare $cur < end]} {\n\
set text \"$text[$w get $cur \"$cur lineend + 1c\"]\"\n\
set pos [$op $text 0]\n\
if {$pos >= 0} {\n\
return [$w index \"$start + $pos c\"]\n\
}\n\
set cur [$w index \"$cur lineend +1c\"]\n\
}\n\
return end\n\
}\n\
proc tkTextPrevPos {w start op} {\n\
set text \"\"\n\
set cur $start\n\
while {[$w compare $cur > 0.0]} {\n\
set text \"[$w get \"$cur linestart - 1c\" $cur]$text\"\n\
set pos [$op $text end]\n\
if {$pos >= 0} {\n\
return [$w index \"$cur linestart - 1c + $pos c\"]\n\
}\n\
set cur [$w index \"$cur linestart - 1c\"]\n\
}\n\
return 0.0\n\
}\n\
";
